### ISSUE TITLE
Add support targets.vim

### ISSUE THREAD

**Issue by CRAG666** [kylechui/nvim-surround#1]
Add support for https://github.com/wellle/targets.vim:
Example of what could be achieved if using targets in this plugin:

csq" change any quote for ""
csq' change any quote for '

csb{ change any bracket for {}
dsb delete any bracket

etc..

This is much faster than using the default way. This will open many possibilities. I would like to have this. Thank you very much. It's an excellent plugin :)

**Comment by kylechui** [comment]
Hmm... this project looks quite interesting---I'll definitely take some time to check it out. However, I'm still working out how to clean up the code and make it more maintainable, as well as patch some unintended behavior. Thanks for the kind words!

**Comment by kylechui** [comment]
After looking into it a bit more, I think that I might not implement *everything* that `targets.vim` does, but I'll try to at least add the aliases feature (i.e. `q` representing both `'` and `"`). Behind the scenes, the plugin is running largely off of `operatorfunc` and not much more, so if I were to try adding things like `ci,` I would probably have to write a lot of text parsing myself, which I don't really have the time for at the moment. I'll keep it in mind for the future though!

**Comment by CRAG666** [comment]
The alias approach might be the best; my point is to streamline the use of commands eg b = {, [, etc. or q = ` ' ", etc. or t = any tag(<h1> etc.).
This gives the possibility to delete, change etc. As I said, it is easier to do this:

cst<h2>
csq'
dsq
dst
dsb
csb[
etc.

**Comment by kylechui** [comment]
Yeah, that makes sense, I was mainly saying that I was going to put off implementing motions like `2cib` and `ci,` for now, as they seem more involved. Looking through the code more closely, it looks like everything is parsed manually and does not use `operatorfunc`. I'll try my hand at implementing aliases soon, once I have the time.

**Comment by kylechui** [comment]
Honestly, I might just start rewriting the code base now since I think `operatorfunc` is getting in the way of me trying to accomplish other things. Hopefully it doesn't take too long so I can focus on implementing new features (i.e. aliasing, HTML tags, etc).

**Comment by kylechui** [comment]
Just as a small update: I've started work on another plugin called `nvim-targets` which tries to give access to a few more textobjects, i.e. aliasing different quotes via `q` or being able to refer to `,` as a surrounding delimiter. I've been a bit busy lately with school and stuff, but hopefully I'll have more time to work on this once the year's over. I also want to try my hand at using Treesitter to implement changing/deleting surrounding HTML tags.

**Comment by CRAG666** [comment]
This is incredible, I hope you can dedicate time to it, by the way, good luck with your studies. I already finished the race but I know how difficult it is. Greetings

**Comment by kylechui** [comment]
Hello! I think I've finished recovering from last quarter, I'll probably try to work on implementing this tomorrow!

**Comment by kylechui** [comment]
I've written a very basic version of aliasing over on the `add-aliasing` branch, so far all it supports is deleting quotes via `dsq`. If you want, feel free to give it a try and let me know what you think

**Comment by CRAG666** [comment]
awesome, more funtions please
