### ISSUE TITLE
Do I need packer to install it?

### ISSUE THREAD

**Issue by phcerdan** [kylechui/nvim-surround#104]
I am new to lua environments. Do I specifically need `packer` for installation, or vim managers like `vim-plug` would work?

Thanks!

**Comment by kylechui** [comment]
Vim-plug would work perfectly fine as well:
```vim
Plug "kylechui/nvim-surround"
```
should work.

**Comment by phcerdan** [comment]
Hi @kylechui, not working for me. `yss` for example works when I use vim-surround, but not with this.
I can access the help function `:help nvim-surround`, and the plugin seems installed correctly, but there are no default mappings.
Do I have to explicitly enable mappings or anything else for installation with `vim-plug`?

**Comment by kylechui** [comment]
Ah, I forgot to mention that you need to run the setup function as well. You can do that using
```viml
lua << EOF
require("nvim-surround").setup()
EOF
```
I think; I'll need to look into the syntax a bit more later.

**Comment by phcerdan** [comment]
That was it. Thanks!
