### ISSUE TITLE
Latest commit doesn't work at all

### ISSUE THREAD

**Issue by languitar** [kylechui/nvim-surround#111]
**Checklist**
- [x] Have you updated the plugin to the latest version on `main` branch?
- [x] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [x] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

**Describe the bug**

Commit https://github.com/kylechui/nvim-surround/commit/306a92830ede75d7d3a48ba04c7e603b73c3f377 doesn't work at all. Keymaps are not registered at all. Going back to the previous commit makes this plugin work again.

**Comment by kylechui** [comment]
That is quite bizarre; I'll look into this as soon as I'm able to get to my computer.

**Comment by languitar** [comment]
That's weird. I have the feeling this was a packer error. Now after getting back to the main branch things still work on the most recent commit and I can't reproduce the error anymore. 🤷 So this issues probably wasn't related to nvim-surround. Sorry for the noise.

**Comment by kylechui** [comment]
No worries, glad to know it wasn't an error on my end haha :laugh:

**Comment by archiif** [comment]
I was having the same issue, I think running `:PackerCompile` fixed the issue, not so sure though.

**Comment by kylechui** [comment]
Hmm... that's quite strange. I'm about to (maybe in the next few days) release a massive update (see branch `pattern-matching`), so hopefully that branch fixes this, if it exists at all.
