### ISSUE TITLE
Option to disable "Invalid Character!" red message

### ISSUE THREAD

**Issue by ziontee113** [kylechui/nvim-surround#118]
**Checklist**
- [x ] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

**Is your feature request related to a problem? Please describe.**
The "Invalid Character!" red message is very aggressive. I'd like to turn it off, or replace it with a simple `print()` statement.

**Describe the solution you'd like**
An option to disable / change that message.

**Additional context**
I tried this code and it didn't work, what am I doing wrong?
```lua
require("nvim-surround").setup({
	delimeters = {
		invalid_key_behavior = function() print("ok cool") end,
	},
})
```

Thank you very much.

**Comment by kylechui** [comment]
It appears you have spelled "delimiters" wrong.

**Comment by ziontee113** [comment]
Thank you very much :) Silly me :joy:
