### ISSUE TITLE
Remove whitespace with ( 

### ISSUE THREAD

**Issue by petobens** [kylechui/nvim-surround#122]
Hi if I have a something like: `[foo]` and I press `cs[(` then I get `[ foo ]`. I would like open parenthesis to avoid adding the leading/trailing whitespace (i.e basically swap the default behaviour of `(` for `)`)? Is that possible?  I had something working prior to todays changes with:
```lua
require('nvim-surround').setup({
    delimiters = {
        pairs = {
            ['('] = { '(', ')' },
        },
}})
```
but that is not working anymore.. Thanks in advance!

**Comment by kylechui** [comment]
See the breaking changes issue (#77), many changes have been made to configuration that break things. You're going to want to put the table under the `add` key.

**Comment by petobens** [comment]
Hi! I indeed saw that but if I add:
```lua
require('nvim-surround').setup({
    surrounds = {
        ['('] = {
            add = { '(', ')' },
        },
    },
})
```
and then for instance try `ds(` on `(foo)` it won't work  since I probably also need to add a `delete` entry to the `surrounds` table.. My question therefore is: is there an easy way to simple map/swap `(` to have the same of `)` for add, delete and change?

**Comment by kylechui** [comment]
You can set the `(` surround to false, then alias `(` to `)` in the `aliases` table. See the default configuration for examples

**Comment by kylechui** [comment]
> Hi! I indeed saw that but if I add:
> 
> ```lua
> require('nvim-surround').setup({
>     surrounds = {
>         ['('] = {
>             add = { '(', ')' },
>         },
>     },
> })
> ```
> 
> and then for instance try `ds(` on `(foo)` it won't work since I probably also need to add a `delete` entry to the `surrounds` table.. My question therefore is: is there an easy way to simple map/swap `(` to have the same of `)` for add, delete and change?

Also with respect to why your original setup didn't work: you are correct that you would need to provide find/delete keys; they were defaulting to the `invalid_key_behavior` behavior, and was trying to delete `{, '(', '(' }` pairs.

**Comment by petobens** [comment]
Thanks!

**Comment by kohane27** [comment]
just want to leave a comment for OP: I had the exact same issue. And of course, thank you kylechui for providing the exact solution we need!
