### ISSUE TITLE
Suggested refactor of vim.tbl_extend()

### ISSUE THREAD

**Issue by andrewferrier** [kylechui/nvim-surround#13]
You can probably use `vim.tbl_extend()` or `vim.tbl_deep_extend()` here: https://github.com/kylechui/nvim-surround/blob/0885e555fff2f7b36e446283f3e9a35fcdfef5b5/lua/nvim-surround/config.lua#L63

**Comment by kylechui** [comment]
Thank you so much for the suggestion! I didn't realize that a builtin function to do this already existed. I'll be closing this issue as I've added it in [the latest commit](https://github.com/kylechui/nvim-surround/commit/2828690dd7b35f6251ce00c2e5d5b50c98bddc6e).
