### ISSUE TITLE
Make keymap for surrounding words with quotations

### ISSUE THREAD

**Issue by dlvhdr** [kylechui/nvim-surround#134]
**Checklist**
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

**Is your feature request related to a problem? Please describe.**
I'm trying to set the following keymap:
`vim.keymap.set("n", '<Leader>"', 'ysiW"', { silent = true })`
I want it to surround words with quotations.
Maybe I just don't know how to write this keymap.

**Comment by smjonas** [comment]
You could use `vim.keymap.set('n', '<Leader>"', '<cmd>norm ysiW"<cr>')`

**Comment by dlvhdr** [comment]
Thank you, I'll check that out

**Comment by kylechui** [comment]
What Jonas sent should work; an alternative keymap is the following:
```lua
vim.keymap.set("n", '<Leader>"', function()
    return 'ysiW"'
end, { remap = true, expr = true })
```
