### ISSUE TITLE
Use the appropriate replacement function for aliases

### ISSUE THREAD

**Issue by haoming-li-ling** [kylechui/nvim-surround#139]
I have an alias for two surrounds, both of which have replacement functions defined in the `change` table. When I invoke a change of surrounds (`cs<alias>`) with the alias, however, neither replacement function is applied, and the behavior falls back to waiting for a single surround character. I think the desired behavior should be to apply the replacement that belongs to the actual surrounds triggered by the alias in the context.

**Comment by kylechui** [comment]
Can you provide an example of what is exactly the problem? Like your setup function + buffer + keymap combo?

**Comment by kylechui** [comment]
Sample config:
```lua
require("nvim-surround").setup({
    surrounds = {
        [")"] = {
            change = {
                replacement = { "(", ")" },
            },
        },
        ["}"] = {
            change = {
                replacement = { "{", "}" },
            },
        },
    },
    aliases = {
        ["o"] = { ")", "}" },
    },
})
```

**Comment by kylechui** [comment]
Note to self: When computing nearest selection, return which character from the alias table was actually used to find the selections.

**Comment by kylechui** [comment]
Closing this as it seems to incur high cost for little utility, and is related to #98.
