### ISSUE TITLE
Error changing surrounds (the latest commit)

### ISSUE THREAD

**Issue by garyzhang2002** [kylechui/nvim-surround#14]
I tried to change the surrounds using `cs'"` as usual when I encountered this error:

![image](https://user-images.githubusercontent.com/24851999/177041559-fab4c003-12c2-4c42-94c5-b1ec3c4b4126.png )

It turned out that `ds` also errored out. `ys` and `S` functioned correctly though.
And I found out these only happened in the latest commit [0885e555fff2f7b36e446283f3e9a35fcdfef5b5](https://github.com/kylechui/nvim-surround/commit/0885e555fff2f7b36e446283f3e9a35fcdfef5b5).

Then I tried to use the previous commit [980070a9b3b55dd321d729a51a8c820f181ca14f](https://github.com/kylechui/nvim-surround/commit/980070a9b3b55dd321d729a51a8c820f181ca14f) and everything worked perfectly fine.

**Comment by kylechui** [comment]
Hi there, do you mind testing the code out on my `implement-dot-repeat` branch found [here](https://github.com/kylechui/nvim-surround/tree/implement-dot-repeat), I made a few other commits that change the overall structure of the code. Let me know if things are still broken, thanks!

**Comment by garyzhang2002** [comment]
> Hi there, please test the code out on my `implement-dot-repeat` branch found [here](https://github.com/kylechui/nvim-surround/tree/implement-dot-repeat), I made a few other commits that change the overall structure of the code (and hopefully make things more stable). Let me know if things are still broken, thanks!

I have just tested those four operations I mentioned above and everything seemed working fine with your latest commit [107291fd355d43dc1e9c38cf2f60ad26ee969a42](https://github.com/kylechui/nvim-surround/commit/107291fd355d43dc1e9c38cf2f60ad26ee969a42) in the `implement-dot-repeat` branch 😃.

**Comment by kylechui** [comment]
Perfect! If anything crops up again, feel free to re-open this issue and let me know
