### ISSUE TITLE
Could i map like this `map('n', "<leader>'", "ysiw'")`

### ISSUE THREAD

**Issue by ShiChenCong** [kylechui/nvim-surround#144]
**Checklist**
- [x] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

**Is your feature request related to a problem? Please describe.**
i'd like to map like this
```lua
map('n', "<leader>'", "ysiw'")
map('n', '<leader>[', 'ysiw[')
map('n', '<leader>{', 'ysiw{')
map('n', '<leader>(', 'ysiw(')
```

**Describe the solution you'd like**
successful mapping

**Additional context**
Thank you for the awesome work

**Comment by kylechui** [comment]
Please see #134 for information. TL;DR you need `remap = true`, since `vim.keymap.set` does not enable that option by default.

**Comment by ShiChenCong** [comment]
works,thank you
