### ISSUE TITLE
[Bug] When used with which-key.nvim the insert surround operator outputs g@

### ISSUE THREAD

**Issue by akinsho** [kylechui/nvim-surround#15]
Hi,

Was quite interested to try this plugin out, but it seems to conflict with using `which-key.nvim` when pressing `ysiw'` it stops at the `ys` and inserts `g@` into the buffer instead of completing the mapping. Some other mappings such as `cs` also seem to encounter this issue.

This though isn't a problem for `vim-surround` which completes the mapping without issue.

Details:
nvim version: nightly
os: macOS 12.3

This is not a huge amount of detail, apologies. I assume that if you try this plugin with which key, you will be able to easily reproduce this behaviour. If not, please let me know, and I'll try to add more information.

**Comment by kylechui** [comment]
Hi there, do you mind testing out my `implement-dot-repeat` branch instead of `main`? It seems like `main` is a bit buggier than the other branch; I might merge earlier than I had intended

**Comment by akinsho** [comment]
@kylechui just gave that a try, and it still seems to be broken, unfortunately pressing `ys` → `i` or `a` just enters `g@` into the buffer

**Comment by kylechui** [comment]
Hmm that seems quite strange, I tried this minimal config:
```lua
return require("packer").startup(function()
    use("wbthomason/packer.nvim")
    use({
        "kylechui/nvim-surround",
	branch = "implement-dot-repeat",
        config = function()
            require("nvim-surround").setup({})
        end,
    })
    use({
        "folke/which-key.nvim",
        config = function()
            require("which-key").setup({})
        end,
    })
end)
```
and wasn't able to reproduce it. I wonder if it's something to do with MacOS or the latest nightly, as another user (#11) also had a similar issue with conflicting keybinds that I can't replicate. I'll try installing the nightly right now and see if that's the case.

**Comment by akinsho** [comment]
@kylechui did a bit more debugging and it seems it was actually https://github.com/Matt-A-Bennett/vim-surround-funk interacting with the `ys` mappings for some reason although `vim-surround` doesn't seem to mind. With that plugin disabled it works fine but one issue I'm still seeing which does seem related to which key is using the `cs` mapping. This seems to block input when I try and change surrounding quotes. Till I press `<c-c>` which then prints

<img width="1483" alt="image" src="https://user-images.githubusercontent.com/22454918/177058044-6825bcd9-b13c-4c8d-9444-34ca25cdd202.png">

**Comment by kylechui** [comment]
Hmm I don't actually use which-key, so I'm not entirely sure what mappings it has setup by default that could be conflicting with nvim-surround. As for the `<C-c>` issue, it looks like it might be builtin behavior(?), as I'm using `vim.fn.getchar()` to get the character inputs from the user. I will look into whether there's a way to suppress the error message or redirect it some other way

**Comment by kylechui** [comment]
![image](https://user-images.githubusercontent.com/48545987/177058491-09ec2436-e3ab-49fa-85e1-5b4e8f468633.png)
@akinsho I learned that `:checkhealth which_key` exists, and it doesn't look like which-key should have any keymap conflicts with nvim-surround by default, so I think vim-surround-funk is most likely the culprit. I don't know how vim-surround-funk is implemented, but I suspect the author wrote it with vim-surround in mind to avoid any potential conflicts.

**Comment by akinsho** [comment]
@kylechui thanks for having a go with which key, so just to clarify I have *fully disabled* surround funk, so I don't believe it is related to the issue I'm seeing with nvim-surround. I think it caused the `ys` issue, but I don't know what is causing the `cs` issue. I had a brief look at its code and I don't believe it does any special case handling to escape issue with `vim-surround`. 

I'm not a 100% sure but I think something about how the surrounds are being applied is "leaking" since using either `vim-surround-funk` or `vim-surround` which both use the operator function don't cause these interactions.

The issue with `<c-c>` and `getchar` is fairly trivial to fix since if you wrap the function with `pcall` that will swallow any error it throws.

**Comment by kylechui** [comment]
Thanks for the tip about `pcall`, just pushed a change to `implement-dot-repeat` that fixes it. I see that in the screenshot you have a `set opfunc=v`, which looks like something I'm using to find selections in nvim-surround, but only partially filled. I think somehow they are both getting triggered at the same time, but I'm not sure how/why; I'll try to read more about how to use which-key

**Comment by kylechui** [comment]
> I'm not a 100% sure, but I think something about how the surrounds are being applied is "leaking" since using either vim-surround-funk or vim-surround which both use the operator function don't cause these interactions.
I think it might have to do with the fact that some of the mappings in vim-surround-funk are prefixes of nvim-surround's (e.g. `ysf` from vim-surround-funk and `ys` from nvim-surround). I'll install it and see if I run into similar issues or not.

**Comment by kylechui** [comment]
@akinsho Running `:verbose nmap ys` yields the following screenshot:
![image](https://user-images.githubusercontent.com/48545987/177059404-02029669-ad58-4a3a-a9f4-9e546dec1ab9.png)
If you try typing `ys` and waiting ~1-2s for it to timeout, then you can finish the rest of the nvim-surround mapping and it works normally, e.g. `ys` wait `iw)`

**Comment by kylechui** [comment]
Hi @akinsho, please update to the latest commit on branch `implement-dot-repeat` to see if the issue persists; I changed all the keymaps to `expr = true` and it seems to have fixed the issue on my end.

**Comment by akinsho** [comment]
That seems to have fixed the issues @kylechui 🙌🏿 thanks

**Comment by kylechui** [comment]
Do you mind running a minimal config for me just to see if it might be *another* plugin or how you setup the plugins that might be the issue?
```lua
    use({
        "kylechui/nvim-surround",
        config = function()
            require("nvim-surround").setup()
        end,
    })
    use({
        "ggandor/leap.nvim",
        config = function()
            require("leap").set_default_keymaps()
        end,
    })
    use({
        "folke/which-key.nvim",
        config = function()
            require("which-key").setup({})
        end,
    })
```

**Comment by akinsho** [comment]
@kylechui I've manage to boil it down to a mapping actually

```lua
vim.cmd("packadd nvim-surround")

vim.keymap.set("c", "::", "<C-r>=fnameescape(expand('%:p:h'))<cr>/") -- THIS TRIGGERS IT
require("nvim-surround").setup()
```

It seems it's actually not related at all to which-key and is actually because somehow that mapping gets triggered, and it blocks nvim waiting for command line input.

I don't know why the commandline is being triggered there, but one other side effect of this is that it cause the comamndline to flash up if using `cmdheight=0` on nightly. I think maybe these mappings should be being executed silently or using `<Cmd>` to stop actually going into the commandline.

**Comment by kylechui** [comment]
@akinsho Sorry for the late reply, but I wasn't able to replicate your issue on a the most recent nightly (`NVIM v0.8.0-dev+550-gf075feee3`) with the following `minimal_config.lua`:
```lua
vim.cmd([[set cmdheight=0]])
vim.keymap.set("c", "::", "<C-r>=fnameescape(expand('%:p:h'))<cr>/")
return require("packer").startup(function()
    use("wbthomason/packer.nvim")
    use({
        "kylechui/nvim-surround",
        config = function()
            require("nvim-surround").setup()
        end,
    })
end)
```
Can you try using the above as well via `nvim -u minimal_config.lua`? Also perhaps the reason for the flickering command line is that in my function to find the selection that the cursor is in, I set an operatorfunction using `:set opfunc=...`; I will try your suggestion of changing it to `<Cmd>` and `silent` to see if that helps

**Comment by akinsho** [comment]
@kylechui apologies for the run around, it turns out this issue does need which key to reproduce. Please try
```lua
vim.cmd("packadd nvim-surround")
vim.cmd("packadd which-key.nvim")

vim.keymap.set("c", "::", "<C-r>=fnameescape(expand('%:p:h'))<cr>/")
require("nvim-surround").setup()
require("which-key").setup()
```
then `nvim -u <config-above.lua>`

and then if you enter some text and then surround it, then try and change or remove the surrounds you'll see the cursor block.

Sorry I was initially trying it with which key but when I saw it was due to a mapping I just assumed that which key wasn't related but it still is.

**Comment by kylechui** [comment]
I've finally been able to reproduce the issue (somewhat); the command line flashes for me and says `Press ENTER or type command to continue`, and then doesn't delete nor change the surrounding pair. It appears that adding surrounds still works, so I think I know where to start looking through the code.
P.S. No worries for the run around, glad we were just able to finally narrow it down to something!

**Comment by kylechui** [comment]
@akinsho The strangest thing is happening now; it *doesn't* work for me with a minimal config, but *does* when I use my default config that I use for everything else (with which-key included). I still see the flickering `Press ENTER or type command to continue`, but it seems to just skip past it and move on, modifying the buffer as intended. At the very least the `fix-keymaps` branch shouldn't *hang* anymore, but might still have some issues with actually performing the action.

**Comment by akinsho** [comment]
@kylechui thanks, that works now 👍🏿. Think that's all the issues I had resolved. Great work 🚀
