### ISSUE TITLE
ds} deletes one paren above instead of current surround

### ISSUE THREAD

**Issue by uloco** [kylechui/nvim-surround#152]
### Checklist

- [X] Have you updated the plugin to the latest version on `main` branch?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

### To reproduce

https://user-images.githubusercontent.com/8818340/190410044-563cfc1f-9ee2-4ef0-93d1-1fb0ffabbb3e.mov

I just press cs} in the bottom part. it always jumps to the top part. also when i do ds}. it only does for the current when i do cs{ which is weird and not what should happen. This also happens with other parens like ] and )

### Expected behavior

should always respect current surrounding braces when used with `}`, `{` should just take whitespace into account also.

**Comment by kylechui** [comment]
Are you using the tagged version or `main` branch? Please try switching to the other and let me know if that changes anything.

**Comment by uloco** [comment]
I was indeed on the tagged version and updating to latest fixed this for me, ty.

**Comment by kylechui** [comment]
That's good to hear! I'm still trying to work on the latest version when I have the time, so hopefully I'll be able to release a new version at some point this year.
