### ISSUE TITLE
Running action such as `dsq` changes last visual selection marks

### ISSUE THREAD

**Issue by smjonas** [kylechui/nvim-surround#154]
### Checklist

- [X] Have you updated the plugin to the latest version on `main` branch?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

### To reproduce

1. Select a range of text in a buffer:
![image](https://user-images.githubusercontent.com/40792180/192098735-a7444f94-b6e2-41b6-8c01-7f047b04b638.png)

3. Now run a nvim-surround command, e.g. `dsq`
4. Run `gv` to reselect the last visually selected lines.

### Expected behavior

The lines selected in step 1 should be visually selected.

### Actual behavior

The position from the first quote to the last one (here: `"packer.nvim"`) is selected.

### Additional context

This behavior causes some issues with a plugin of mine so it would be great if  the `'<` and `'>` marks were restored after a command is run. I'll try to make a PR :)

**Comment by kylechui** [comment]
Apologies for being inactive these last few weeks; school + life is one hell of a combo. I'll try to make time to review your PRs sometime this upcoming week.

**Comment by smjonas** [comment]
Thanks for taking the time to merge this!

**Comment by kylechui** [comment]
Thanks for taking the time to write the PR! It really helps out a lot, even if it's small. :sparkling_heart:
