### ISSUE TITLE
Cancelling changing function name results in null

### ISSUE THREAD

**Issue by koengommers** [kylechui/nvim-surround#159]
### Checklist

- [X] Have you updated the plugin to the latest version on `main` branch?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

### To reproduce

Press `Esc` in the prompt after doing `csf`. Occurs in at least Lua and Typescript.

### Expected behavior

Leave the function name as it was

### Actual behavior

Replaces function name with 'null'

**Comment by kylechui** [comment]
Please update to Neovim version 0.8, see #150
