### ISSUE TITLE
Adds delimiters in the wrong place when using `ip` text object

### ISSUE THREAD

**Issue by andrewferrier** [kylechui/nvim-surround#16]
Recreation:

* Configure and install nvim-surround
* With some paragraph-separated text like this:

```
aaa
bbb
ccc

ddd
eee
fff

ggg
hhh
iii
```

* Position cursor over `eee`, and type `ysip"`

Observed:

* The ending double-quote is positioned at the beginning of the line `fff`

Expected:

* The ending double-quote is positioned directly after the `fff`, i.e.:

```
aaa
bbb
ccc

"ddd
eee
fff"

ggg
hhh
iii
```

In essence, I think you are missing out the last line of the paragraph. This is also how `vim-sandwich` operates, and I suspect `vim-surround` (although I haven't installed the latter to check it).

**Comment by kylechui** [comment]
TIL that `vip` actually selects the paragraph using visual *line* mode, not char mode; I suspect that the marks are set on the first character of both lines instead of the "proper" characters; I'll start work on this after I finish some of the work on the other issues

**Comment by kylechui** [comment]
@andrewferrier Please try updating to the latest commit on main, see if that fixes things here

**Comment by andrewferrier** [comment]
Yes, this seems to work now, thanks!
