### ISSUE TITLE
Weird behaviour with cyrillic characters

### ISSUE THREAD

**Issue by biozz** [kylechui/nvim-surround#168]
### Checklist

- [X] Have you updated the plugin to the latest version on `main` branch?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

### To reproduce

Sample buffer:

```
this is english
а это русский
```

Starting from the beginning of the document type: `v$S)`. (visually surround the line)

Then go to the beginning of the next line and do the same.

### Expected behavior

I expect the plugin to work the same on both lines and get this:

```
(this is english)
(а это русский)
```

Without breaking the encoding.

### Actual behavior

Instead I see something like that:

```
(this is english)
(а это русски<d0>)<b9>
```
Those `<d0>` and `<b9>` are greyed out like control characters.

It also breaks the file encoding. After I open the file again I get:

```
(this is english)
(Ð° ÑÑÐ¾ ÑÑÑÑÐºÐ¸Ð)¹
```

And if I do `:set fileencoding`, it shows `latin1` instead of `utf8`.

Note that I have properly set `encoding` and `fileencoding` to `utf-8` in my config.

**Comment by kylechui** [comment]
My guess is that this has to do with surrounding multi-byte characters (which I thought I fixed), but I'll look into it when I have the time.

**Comment by kylechui** [comment]
I'm actually unable to replicate this issue. Can you send me what version of Neovim you're using, as well as if you're using the nightly version of this plugin? In any case, please try updating your plugin to see if it fixes things.

**Comment by kylechui** [comment]
I tried `nvim --clean` and put in the sample text that you gave, and also tried using the stable release of the plugin. Unfortunately, I was still unable to replicate the issue. If possible, could you also provide a minimal configuration via `nvim -u minimal_config.lua` that produces the issue?

**Comment by biozz** [comment]
I think it has to do with one of or a combination of `dhruvasagar/vim-table-mode` and `preservim/vim-markdown`. I tried disabling those and it worked. I also enabled them back and it works as well. 🤷‍♂️ 

Not sure if it needs further investigation. My issue is resolved (for now). Feel free to close the ticket.

Thanks again for the suggestions.

**Comment by kylechui** [comment]
Yeah I'm not 100% sure what it could be either, if you didn't update your other plugins. Feel free to re-open this issue if the bug pops up again, with a minimal config and steps to reproduce it
