### ISSUE TITLE
Deleting brackets behavior 

### ISSUE THREAD

**Issue by darkangel-ua** [kylechui/nvim-surround#177]
HI there! After sometime I've noticed that if I try to delete `{` brackets that are placed like this
```
if (true) 
{
    foo();
}

bar();
```
I end up with this 
```
if (true) 

    foo();


bar();
```
but I clearly remember that previously `ds{` removed empty lines also. I couldn't find any mention about this. How I can fix that?

**Comment by kylechui** [comment]
See 163.
