### ISSUE TITLE
Add description for default keymaps

### ISSUE THREAD

**Issue by Tummetott** [kylechui/nvim-surround#187]
Hey there. 
First of all, great plugin!! I recently switched from tpopes vim-surround and I don't want to go back 👍 

My question: It would be nice if the default keymaps have a description. Descriptions are usefull for showing a help window with e.g. 'which-key.nvim' or for debugging.

Also user defined keymaps within the setup function could benefit from a description. One possible example:
```lua
setup = {
    keymaps = {
        normal = { mapping = "ys", desc = "Surround textobject with pair" }
        normal_cur = { maping = "yss", desc = "Surround the current line with pair" }
        ...
    },
}
```

**Comment by kylechui** [comment]
Hi, are you using the tagged version of the plugin? Keymap descriptions should be active in the latest (untagged) commit.

**Comment by Tummetott** [comment]
I'm loading the plugin without tag. But when pressing `ys`, my `which-key` popup shows

![image](https://user-images.githubusercontent.com/19708025/208913414-34ceaf45-c9c2-4219-927a-bc178e0367e4.png)

**Comment by kylechui** [comment]
Ah, it appears that I put the keymap descriptions on the internal binds by mistake; I'll fix it when I get the chance (or if anyone wants to make a PR that would be much appreciated)

**Comment by kylechui** [comment]
This should be fixed in the latest commit; if it isn't then feel free to re-open
this issue!

**Comment by Tummetott** [comment]
Awesome thank you ❤️

**Comment by trevarj** [comment]
It would still be neat to be able to add a custom description by changing the [hardcoded ones](https://github.com/kylechui/nvim-surround/blob/633a0ab03159569a66b65671b0ffb1a6aed6cf18/lua/nvim-surround/config.lua#L682C11-L682C11). Is this not possible now?
