### ISSUE TITLE
Error on custom surrounds.

### ISSUE THREAD

**Issue by D00mch** [kylechui/nvim-surround#191]
### Checklist

- [X] Have you tried updating the plugin to the latest version?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

### Neovim Version

```
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
```

### Plugin Version

Tagged (Stable)

### Minimal Configuration

```lua
setup({
  surrounds = {
   ["("] = {add = {{"("}, {")"}}},
    c = {add = {{"#_"}, {""}}},
  }
})
```

### Sample Buffer

```clojure
(ns dumch.play)

(defn a [])
```

### Keystroke Sequence

`ysaw(`, `ysa(c`

### Expected behavior

Command: `ysa(c`
Cursor: `|`.

Before:
```
(|defn a [])
```
After:
```
`#_|(defn a [])
```

### Actual behavior

Error executing lua... buffer.lua:203: Expected lua table

![image](https://user-images.githubusercontent.com/14236531/209967140-3b2ee81b-a151-49e9-87e4-1d1501805f67.png)

### Additional context

This began to happen after the last three commits. This one works: f0077c3726d243eeaabd2ec280216e8c3ca7da9f

While submitting this issue, I discovered that if I rewrite my config, everything works, but I decided to create an issue anyway so that others could find it.

```lua
setup({
  surrounds = {
   ["("] = {add = {"(", ")"}},
    c = {add = {"#_", ""}},
  }
})
```

**Comment by kylechui** [comment]
Should be fixed in the latest commit; feel free to re-open if the issue persists. Thanks for reporting the bug!
