### ISSUE TITLE
Surround commands not triggered

### ISSUE THREAD

**Issue by rcclemente** [kylechui/nvim-surround#193]
### Checklist

- [X] Have you tried updating the plugin to the latest version?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

### Neovim Version

v0.8.1

### Plugin Version

Tagged (Stable)

### Minimal Configuration

  use({
    "kylechui/nvim-surround",
    tag = "*", -- Use for stability; omit to use `main` branch for the latest features
    config = function()
        require("nvim-surround").setup({
            -- Configuration here, or leave empty to use defaults
        })
    end
  })

### Sample Buffer

require "user.keymaps"

### Keystroke Sequence

cs"'

### Expected behavior

expect double qoutes to replace single quote

### Actual behavior

When pressing the sequence `cs"'` i noticed the after pressing the letter `s` the command disappears in the right corner and nothing is triggered

**Comment by kylechui** [comment]
Are you sure that the plugin has been properly installed via PackerSync or PackerInstall? What is the output of `:lua =pcall(require, "nvim-surround")`?

**Comment by rcclemente** [comment]
![Screen Shot 2023-01-02 at 10 45 57 AM](https://user-images.githubusercontent.com/22880578/210191914-402a8d4c-70b2-48a8-a7ff-ee41fbfb0313.jpg)

HI @kylechui above is the screenshot from the output

**Comment by kylechui** [comment]
Hmm... that is quite strange as you are using the tagged version. I would either try removing then reinstalling the plugin, or do the following:
1. Start Neovim without any configuration using `nvim -u NONE`
2. Setup `nvim-surround` via `:lua require("nvim-surround").setup()`
3. Retry `cs"'` on the buffer of your choice

If neither of the above work, please do steps 1 and 2, then send the output of `:verbose nmap cs`.

**Comment by rcclemente** [comment]
@kylechui thanks i found the problem in my root config... This is working great now
