### ISSUE TITLE
 nvim-surround.jumps bug

### ISSUE THREAD

**Issue by kls1991** [kylechui/nvim-surround#196]
### Checklist

- [X] Have you tried updating the plugin to the latest version?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

### Neovim Version

0.8.1

### Plugin Version

Tagged (Stable)

### Minimal Configuration

Default configuration

### Sample Buffer

vim.keymap.set("n", "\<tab\>", "L{jzt")

use {} --cursor at begin of the line

use {}

### Keystroke Sequence

ds{

### Expected behavior

a pair of {} disappeard

### Actual behavior

nothing

### Additional context

the "{" in keymap seems make nvim-surround.jumps crazy

**Comment by kls1991** [comment]
Oh my, neovim default va{ behave the same in this situation

**Comment by kylechui** [comment]
Please try switching to the untagged version of the plugin (by commenting out `tag = '*'` in your configuration, then re-installing the plugin.

**Comment by kylechui** [comment]
> Oh my, neovim default va{ behave the same in this situation

I would also try `nvim -u NONE` with your test buffer, and then do `va{`. For me, it visually selects the curly braces.

**Comment by kylechui** [comment]
Ah, sorry for misreading your issue. It does seem to be a problem "upstream" with Neovim itself; you could try changing the `find` key for `{` to use Lua patterns instead, but that would also have its drawbacks (I think worse handling for escaped `{`, etc.)
