### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by angelollima** [kylechui/nvim-surround#198]
### Checklist

- [X] Have you tried updating the plugin to the latest version?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

### Neovim Version

NVIM v0.8.2

### Plugin Version

Tagged (Stable)

### Minimal Configuration

  ```lua
use({
    "kylechui/nvim-surround",
    tag = "*", -- Use for stability; omit to use `main` branch for the latest features
    config = function()
      require("nvim-surround").setup({
        -- Configuration here, or leave empty to use defaults
      })
    end
  })
```

### Sample Buffer

![image](https://user-images.githubusercontent.com/98702765/212911362-19d54d8d-c53b-4d81-97a1-5f27920e6543.png)

### Keystroke Sequence

:ysiw)

### Expected behavior

"kylechui/nvim-surround"

command: ysiw)

expected:  ("kylechui/nvim-surround")

### Actual behavior

nothing happens and then i receive the message Error "Not an editor command"

### Additional context

I saw the issue https://github.com/kylechui/nvim-surround/issues/193#issue-1515083889 but i believe that there's no problem on root cause i tested others plugins after i try this one and it works well!

**Comment by kylechui** [comment]
That is because `ys` is not an editor command defined by `nvim-surround`. It is a normal mode keymap, i.e. type `ysiw)` *in normal mode*, not in command mode.

**Comment by angelollima** [comment]
i'm so sorry for that. I got completely confused. works pretty well
