### ISSUE TITLE
What Jonas sent should work; an alternative keymap is the following:

### ISSUE THREAD

**Issue by angelollima** [kylechui/nvim-surround#199]
What Jonas sent should work; an alternative keymap is the following:
```lua
vim.keymap.set("n", '<Leader>"', 'ysiW"', { remap = true })
```
or
```lua
vim.keymap.set("n", '<Leader>"', function()
    return 'ysiW"'
end, { remap = true, expr = true })
```

_Originally posted by @kylechui in https://github.com/kylechui/nvim-surround/issues/134#issuecomment-1211022288_
            

it's not working for me, any other alternatives?

**Comment by smjonas** [comment]
Both of them should work. What exactly happens when you type `<leader>"`?

**Comment by angelollima** [comment]
literally nothing

**Comment by angelollima** [comment]
actually <cr> is not working for me but <CR> is!! thanks for the attention, have a good one!
