### ISSUE TITLE
Setting any option in `keymaps` to an empty string yields error

### ISSUE THREAD

**Issue by luiz00martins** [kylechui/nvim-surround#204]
### Checklist

- [X] Have you tried updating the plugin to the latest version?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

### Neovim Version

NVIM v0.9.0-dev-849+g7880eeb2e

### Plugin Version

Tagged (Stable)

### Minimal Configuration

```lua
require('nvim-surround').setup {
	keymaps = {
		insert = "",
		insert_line = "",
		normal = "s",
		normal_cur = "ss",
		normal_line = "yS",
		normal_cur_line = "ySS",
		visual = "s",
		visual_line = "S",
		delete = "ds",
		change = "cs",
	},
}
```

### Sample Buffer

_none_

### Keystroke Sequence

_none_

### Expected behavior

The mapping would be ignored (not created).

### Actual behavior

Error:
```
vim/keymap.lua:0: Invalid (empty) LHS

# stacktrace:
  - vim/keymap.lua:0 _in_ **set**
  - .config/nvim/init/plugins_portable.lua:1330 _in_ **config**
  - lua:40
```

**Comment by kylechui** [comment]
They should be set to `false` to disable them.

**Comment by luiz00martins** [comment]
Yep, seems to work. Thank you.

Is this not still a bug though? If not, you can close.

**Comment by kylechui** [comment]
No, as setting the LHS of a keymap to an empty string doesn't make sense.
