### ISSUE TITLE
`dsf` deletes an extra character

### ISSUE THREAD

**Issue by pedro757** [kylechui/nvim-surround#207]
### Checklist

- [X] Have you tried updating the plugin to the latest version?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

### Neovim Version

NVIM v0.9.0-dev-869+g964ae205a
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Plugin Version

Latest

### Minimal Configuration

require("nvim-surround").setup()

### Sample Buffer

```jsx
function myFunction(value) {
  return value
}

export default function Page() {
  const somevalue = "something";
  
  return (
    <div onClick={myFunction(somevalue)}>
    
    </div>
  );
}
```

### Keystroke Sequence

With the cursor on `value` in the `onClick` call, use `dsf`

### Expected behavior

```jsx
function myFunction(value) {
  return value
}

export default function Page() {
  const somevalue = "something";
  
  return (
    <div onClick={somevalue}>
    
    </div>
  );
}
```

### Actual behavior

```jsx
function myFunction(value) {
  return value
}

export default function Page() {
  const somevalue = "something";
  
  return (
    <div onClick=somevalue}>
    
    </div>
  );
}
```

### Additional context

The problem here is that it deletes an extra character ( { ) at the beginning

**Comment by kylechui** [comment]
Can you try the untagged version of the plugin and see if the issue persists?

**Comment by pedro757** [comment]
I just checked this out, and it works in the stable version but not in the latest version. I corrected the description of the issue. sorry.

**Comment by kylechui** [comment]
Try the latest commit, it should fix the issue. If not, feel free to re-open this issue.

**Comment by pedro757** [comment]
Thank you, it's working now.
