### ISSUE TITLE
`ysj` not doing the line motion but area motion

### ISSUE THREAD

**Issue by pedro757** [kylechui/nvim-surround#208]
### Checklist

- [X] Have you tried updating the plugin to the latest version?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

### Neovim Version

NVIM v0.9.0-dev-869+g964ae205a
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Plugin Version

Tagged (Stable)

### Minimal Configuration

default

### Sample Buffer

```
I have this text file, and my cursor is here | let's say
then I want to surround these two lines with parenthesis

```

### Keystroke Sequence

ysj(

### Expected behavior

```
( I have this text file, and my cursor is here | let's say
then I want to surround these two lines with parenthesis )

```

### Actual behavior

```
I have this text file, and my cursor is here ( | let's say
then I want to surround these two lines with parenthesis )

```

### Additional context

This is not consistent with the neovim ecosystem, let's consider the yank motion, if I do `yj` it will yank the current line and the next one, that should be the default, then if you need a more specific (certain area) surround you can use visual mode and surround the selected area.

Note: it's the same with `count` motions i.e. `ys4j(`

**Comment by kylechui** [comment]
The latest commit should resolve the bug, and introduces two new tests to ensure that it remains that way. Please feel free to re-open if this doesn't address the problem, and thanks for contributing!

**Comment by pedro757** [comment]
Thank you.
