### ISSUE TITLE
Default Aliases Are Difficult or Impossible to Fully Unset

### ISSUE THREAD

**Issue by mardamkada** [kylechui/nvim-surround#212]
### Checklist

- [X] Have you tried updating the plugin to the latest version?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

### Neovim Version

0.8.3

### Plugin Version

Tagged (Stable)

### Minimal Configuration

```lua
local test_surround = {
    add = { "[bold]" , "[/bold]" },
    find = "%[bold].-%[/bold]",
    delete = "(%[bold])().-(%[/bold])()",
}
require("nvim-surround").setup({
    surrounds = {
        ["b"] = test_surround,
        ["i"] = test_surround,
    },
    aliases = {
        ["b"] = {},
    },
}
```

### Sample Buffer

`[bold]hello[/bold] world`

### Keystroke Sequence

`dsbdsi`

### Expected behavior

the surrounding [bold][/bold] text should be deleted with the `dsb` sequence.

### Actual behavior

surrounding [bold][/bold] text remains after `dsb` but gets deleted with the `dsi` sequence.

### Additional context

Setting the aliases table to empty (i.e. `aliases = {}`) doesn't seem to work at all, whereas setting specific aliases to empty (e.g. `aliases = {["b"] = {}}`) seems to delete the alias but not allow for overwriting the 'ds' and 'cs' keys.

**Comment by kylechui** [comment]
Have you tried setting the alias keys to `false` instead of an empty table?

**Comment by mardamkada** [comment]
I hadn't. That does work. I guess I read the help too hastily and missed that, please excuse the unneeded issue.

**Comment by kylechui** [comment]
No worries, glad to help :)
