### ISSUE TITLE
Delete the wrong pairs

### ISSUE THREAD

**Issue by Nebell** [kylechui/nvim-surround#214]
### Checklist

- [X] Have you tried updating the plugin to the latest version?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [ ] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

### Neovim Version

NVIM v0.8.3
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az171-224

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info

### Plugin Version

Tagged (Stable)

### Minimal Configuration

`use({
        "kylechui/nvim-surround", tag = "*",
        config = function() require("nvim-surround").setup() end,
    })`

### Sample Buffer

`use {''nvim-treesitter/nvim-treesitter-context''}`

### Keystroke Sequence

`use {''nvim-treesitter/nvim-treesitter-context''}`
1. Cursor was on **nvim-treesitter/nvim-treesitter-context**
2. `dsq`

### Expected behavior

`use {'nvim-treesitter/nvim-treesitter-context'}`

### Actual behavior

`use {''nvim-treesitter/nvim-treesitter-context}`

**Comment by gegoune** [comment]
I have also noticed for a while now that when multiple pairs are involved more often than not wrong pair will get selected. Can come up with some examples later.

**Comment by kylechui** [comment]
I assume it is because of [this](https://github.com/kylechui/nvim-surround/issues/77#issuecomment-1309817520). Please use the untagged version and see if it resolves the issue.

**Comment by Nebell** [comment]
> I assume it is because of [this](https://github.com/kylechui/nvim-surround/issues/77#issuecomment-1309817520). Please use the untagged version and see if it resolves the issue.

Thanks, it runs correctly.

**Comment by kylechui** [comment]
Hmm... perhaps it's time for me to make another release, since the current `v1.0.0` has quite a few bugs that have been resolved since then.

**Comment by gegoune** [comment]
Hmm, I observed that behaviour on main branch, didn't use any tags in packer. 

Is it something that needs looking into? Should I come up with some examples?

**Comment by kylechui** [comment]
Yes, @gegoune please create a new issue with the relevant examples, plus a minimal configuration
