### ISSUE TITLE
`cs` pattern is not working on `main` branch

### ISSUE THREAD

**Issue by sxyazi** [kylechui/nvim-surround#217]
### Checklist

- [X] Have you tried updating the plugin to the latest version?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

### Neovim Version

```
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
```

### Plugin Version

Nightly (Beta)

### Minimal Configuration

The [lazy.nvim](https://github.com/folke/lazy.nvim) is my used on:

```lua
{
  "kylechui/nvim-surround",
  event = "BufRead",
  config = function()
    require("nvim-surround").setup({})
  end
}
```

### Sample Buffer

"abc"

### Keystroke Sequence

cs"'

### Expected behavior

'abc'

### Actual behavior

nothing happened

### Additional context

Guessing that is caused by https://github.com/kylechui/nvim-surround/commit/af10059b0f1589a485d9e1b0298172bbf60cdb47, since I checked out the previous commit 1d83fecd27c6b4b66cc529930552d205fbecb660 and all worked fine.

**Comment by kylechui** [comment]
Those commits are from a while ago; can you update to the most recent commit on `main` and see if the issue persists?

**Comment by sxyazi** [comment]
Yes, It still has the issue that using the latest commit on the main.

**Comment by sxyazi** [comment]
I found the problem after rechecking my keymaps and disabling them one by one!

The culprit was this line:

```lua
vim.keymap.set("", "l", "u", { noremap = true })
```

Previously I did check the keymaps associated with the plugin via `:map cs` that found no conflict, and by switching to 1d83fec or tagged v1.0.0 all was well.

Just a bit curious, is that some internal mechanism has used the `l` key? 🤔

**Comment by kylechui** [comment]
Ah shoot, see #197 for more info.
