### ISSUE TITLE
Wrong match when using s as a trigger key

### ISSUE THREAD

**Issue by maxigaz** [kylechui/nvim-surround#235]
### Checklist

- [X] Have you tried updating the plugin to the latest version?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

### Neovim Version

v0.8.3

### Plugin Version

Tagged (Stable)

### Minimal Configuration

```lua
vim.cmd([[let $PLUGIN_DIRECTORY = '~/.local/share/nvim/plugtest']])
vim.cmd([[packadd nvim-surround]])

require("nvim-surround").setup({
  surrounds = {
    -- strong emphasis for markdown
    ["s"] = {
      add = { "**", "**" },
      find = "%*%*.-%*%*",
      delete = "^(%*%*?)().-(%*%*?)()$",
      change = {
        target = "^(%*%*?)().-(%*%*?)()$",
      },
    },
  },
})
```

### Sample Buffer

```markdown
This is a test sentence with **emphasis**.

Another one (for good measure).
```

### Keystroke Sequence

`dss`

### Expected behavior

When the cursor is on `**emphasis**`, pressing the keystroke above deletes the surrounding asterisks, leaving `emphasis`. as a result.

### Actual behavior

The parentheses in the second paragraph are deleted, leaving `Another one for good measure.` as a result.

### Additional context

I adapted the example in [this comment](https://github.com/kylechui/nvim-surround/issues/151#issuecomment-1247901177), where I changed the trigger key from `*` to `s`.

If I change it back to `*` or replace it with another letter such as `e`, it works without any issues.

**Comment by kylechui** [comment]
Have you tried setting the alias `s` to `false` in the setup function? By default, `s` is an alias that matches "any built-in surround".

**Comment by maxigaz** [comment]
I've only tried that just now. It solves the problem. Thank you!
