### ISSUE TITLE
Indent when surrounding multiple lines

### ISSUE THREAD

**Issue by pedro757** [kylechui/nvim-surround#239]
I noticed that when surrounding multiple lines like this 
```html
<h1>My Header</h1>      <!-- type "ysjtdiv" HERE -->
<div>Other Stuff</div>
```

the output is not indented

```html
<div><h1>My Header</h1>
<div>Other Stuff</div></div>
```

It does the indenting when using line visual selection mode and surrounding in that mode
```html
<h1>My Header</h1>     <!-- type "VjStdiv" HERE -->
<div>Other Stuff</div>
```
It works this way, see:
```html
<div>
  <h1>My Header</h1>
  <div>Other Stuff</div>
</div>
```

This issue is related to this other issue #208 

i'm on main latest version btw

**Comment by kylechui** [comment]
First and foremost, sorry for the delay! I've been a bit busy recently with classes and whatnot. I think that the key here is that `ys` won't put delimiters on their own line, so asking to reindent doesn't really make sense IMO. As of right now, the semantics are that stuff that puts delimiters on new lines should re-indent. In your particular use case, does `ySjtdiv` work?

**Comment by pedro757** [comment]
Thank you for your response, I didn't know `yS` was possible, it works, thank you.
