### ISSUE TITLE
Implement `vim.ui.input` over `vim.fn.input`

### ISSUE THREAD

**Issue by kylechui** [kylechui/nvim-surround#24]
Ideally nvim-surround should allow the use of `vim.ui.input` to take in user inputs, to let users modify the look and feel of the inputs (e.g. using [dressing.nvim](https://github.com/stevearc/dressing.nvim)). See #17 and the [the latter half of #5](https://github.com/kylechui/nvim-surround/issues/5#issuecomment-1178257801)

**Comment by kylechui** [comment]
Closing this for now as I still have no clue how this would be done, and the plugin works just fine without `vim.ui.input`

**Comment by nihilistkitten** [comment]
I think I have a solution, if you want to reopen this.

Basic idea: the code here:
https://github.com/kylechui/nvim-surround/blob/04293f3ec9a635b53ff4f3b6fa8cc5789e17e51f/lua/nvim-surround/utils.lua#L49-L54
should be changed to use `vim.ui.input`. As I think you've noticed, it's not a trivial change - `vim.ui.input` is asynchornous and takes a callback.


If we don't want to change the API of `get_input`, probably adding `plenary` as a dependency and using its channels should be a sufficient, if imperfect, solution; we can have the main function block on recieving the value over the channel, and have the callback capture the sender and send the value to the outer scope. I can try to write a PR if you want.

**Comment by kylechui** [comment]
@nihilistkitten If you would like to take a shot at it, be my guest! I will just note that depending on the complexity of the code, I reserve the right to reject such a PR as this is more of a "quality of life" enhancement as opposed to a "real" feature. With that aside, the main issue for me was that although I was able to get some working version done via coroutines, it required non-trivial refactors to all of the functions that *called* `utils.get_input()`, of which there are ~4 (not including the potential ones that users are using for custom surrounds). If you can somehow make this work without sacrificing on simplicity, I'll gladly merge this in :)

**Comment by nihilistkitten** [comment]
Totally makes sense. Should only be a few lines and not super complicated, if definitley moreso, and of course it does add a dependency (albeit a _very_ common one). I'll take a shot at it tonight or tomorrow.

**Comment by nihilistkitten** [comment]
Bleh, ok. Looks like this is a lot more difficult than I thought. What we really want is the ability to block (in a sync context) on the return of an async function, but we don't seem to have that in the language ATM (at least as far as I can tell). Guess this should be close again, unless you want to leave it open for someone with more plenary experience than me :(.

**Comment by kylechui** [comment]
Haha no worries; yeah there's no way to do it without treating "main" as another thread and having to do massive refactors to that instead (to my knowledge). Thanks for the attempt though :)
