### ISSUE TITLE
Allow cmp completion on tag wrapping

### ISSUE THREAD

**Issue by timsofteng** [kylechui/nvim-surround#240]
**Checklist**
- [ x] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

**Is your feature request related to a problem? Please describe.**
In the fronted world tags could be very long (especially with some tools like `styled-components`). It is annoying to print it from scratch if they are existed in the buffer already.

**Describe the solution you'd like**
Cmp completion for buffer would be cool feature to prevent retyping.

**Comment by kylechui** [comment]
This is something that I would love as well, and seems related to [this discussion](https://github.com/kylechui/nvim-surround/issues/145#issue-1350525331). If anyone has ideas as for how this could be done, feel free to let me know!

**Comment by timsofteng** [comment]
@kylechui 

https://github.com/nvim-neo-tree/neo-tree.nvim
I'm not sure that it can helps but file creation works with ability to use cmp in this plugin. Check it please does it make sense or not in context of our discussion.

**Comment by kylechui** [comment]
@timsofteng Does it work in the plugin that you linked? I looked through the issues and [it seems to not work there either](https://github.com/nvim-neo-tree/neo-tree.nvim/issues/820).

**Comment by kylechui** [comment]
Merging this into #145
