### ISSUE TITLE
This plugin breaks `ciw`: it is interpreted as `icw`

### ISSUE THREAD

**Issue by nyngwang** [kylechui/nvim-surround#251]
### Checklist

- [X] Have you tried updating the plugin to the latest version?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

### Neovim Version

```
NVIM v0.10.0-dev-578+g91aeaeef6
Build type: Release
LuaJIT 2.1.0-beta3
```

### Plugin Version

Nightly (Beta)

### Minimal Configuration

```lua
use {
  'kylechui/nvim-surround',
  config = function ()
    require('nvim-surround').setup {

    }
  end
}
```

### Sample Buffer

no need

### Keystroke Sequence

ciw

### Expected behavior

ciw

### Actual behavior

icw

**Comment by nyngwang** [comment]
My current workaround is to define `ci` again using `vim.fn.feedkeys`:

```lua
vim.keymap.set('n', 'ci', function () vim.fn.feedkeys('ci','n') end)
```

**Comment by kylechui** [comment]
Have you updated the plugin to the latest version? Can't reproduce on my end. Also probably try it with all other plugins disabled

**Comment by nyngwang** [comment]
> Can't reproduce on my end. 

My apologies. It turns out to be [another issue](https://github.com/neovim/neovim/discussions/24157#discussioncomment-6277672) as you stated. Let me close this!
