### ISSUE TITLE
Conflicts with leap.nvim

### ISSUE THREAD

**Issue by xbladesub** [kylechui/nvim-surround#253]
How can I remap surround to use some other character, not 's' ? I use leap plugin, seems like leap's bindings have "higher priority" and surround doesn't work at all because of 's'.

**Comment by kylechui** [comment]
`nvim-surround` doesn't use `s` by default at all, see `nvim-surround.config.keymaps` for help with remapping (although I suspect this might be an issue with something else).

**Comment by mrs4ndman** [comment]
Sorry for meddling
If it helps, I got this to work by using this configuration:
- Lazy
```Lua
-- Inside the return { "kylechui/nvim-surround" } statement
opts = {
  keymaps = {
    normal = "ys",
    delete = "ds",
    visual = "S",
    visual_line = "gS",
    change = "cs",
    change_line = "cS",
  }
}
```
- Packer
```Lua
-- In the after/plugin directory or inside the config = function() end block 
require("nvim-surround").setup({
  keymaps = {
    normal = "ys",
    delete = "ds",
    visual = "S",
    visual_line = "gS",
    change = "cs",
    change_line = "cS",
  }
})
```
I use Lazy and leap.nvim / flit.nvim, and this still lets me jump with <kbd>s</kbd> / <kbd>S</kbd> / <kbd>f</kbd> / <kbd>F</kbd> / <kbd>t</kbd> <kbd>T</kbd> and surround things when I need to.

**Comment by kylechui** [comment]
All of the keymaps you listed are default; you should be able to just call `require("nvim-surround").setup()`.

**Comment by kevintraver** [comment]
One of the issues with _**leap.nvim**_, is that the `s` is also mapped in operator mode when using the default keymaps.

So `cs` initiates the **leap** functionality, which conflicts with surround default keymaps.

Same with `ds`.

Instead of using the default *_leap.nvim_* keymaps, you can do something like this:

```
vim.keymap.set({ "n" }, "S", "<Plug>(leap-backward-to)")
vim.keymap.set({ "n" }, "s", "<Plug>(leap-forward-to)")

vim.keymap.set({ "o", "x" }, "Z", "<Plug>(leap-backward-till)")
vim.keymap.set({ "o", "x" }, "z", "<Plug>(leap-forward-till)")
```

or override the `change` (`cs`) and `delete` (`ds`) **_surround_** keymaps

**Comment by Subjective** [comment]
You could also use the mappings suggested by `leap.nvim`'s author.

See https://github.com/ggandor/leap.nvim/discussions/59 and https://github.com/ggandor/leap.nvim/discussions/41 for ideas.

**Comment by theol0403** [comment]
Here's the surround mappings that work the best for me (inspired by linked discussion). Avoids all clashes with leap or flash, by not touching s and instead using `go zurround` as mnemonic. 

```lua
config = {
  keymaps = {
    insert = "<C-g>z",
    insert_line = "<C-g>Z",
    normal = "gz",
    normal_line = "gZ",
    normal_cur = "gzz",
    normal_cur_line = "gZZ",
    visual = "gz",
    visual_line = "gZ",
    delete = "gzd",
    change = "gzc",
  },
  aliases = {
    ["a"] = ">",
    ["b"] = ")",
    ["B"] = "}",
    ["r"] = "]",
    ["q"] = { '"', "'", "`" },
    ["z"] = { "}", "]", ")", ">", '"', "'", "`" },
  },
},
```
