### ISSUE TITLE
Feature parity with vim-surround's `s`

### ISSUE THREAD

**Issue by Kyuuhachi** [kylechui/nvim-surround#255]
**Checklist**
- [x] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

**Is your feature request related to a problem? Please describe.**
tpope/vim-surround has a `s` delimiter, which changes `require("telescope")` to `require "telescope"`. Would be nice to have that.

**Describe the solution you'd like**
Pretty easy to add, though not battle-tested.
```lua
surrounds = {
	["s"] = {
		add = { " ", "" },
	},
}
```

Kinda conflicts with the existing `s`=any delimiter alias, but since you can only change *from* that alias, and can only change *to* this one, it works out pretty well.

**Comment by kylechui** [comment]
I'm not particularly convinced this *needs* to be a built-in for `nvim-surround`, since it's really just a one-off edge case that IMO is quite rare; I would rather people just `nnoremap [something] dsbi <Esc>`.

**Comment by Kyuuhachi** [comment]
Yeah, that's fine too. As mentioned, it's not difficult to add to my local config anyway. It's just that I happened to see that you claimed feature parity in /discussions/55, so.

**Comment by kylechui** [comment]
Yeah fair enough; in the beginning that was more of a goal but I think this plugin has now gotten to most of the use-cases, and I don't really want to add more functionality at the cost of complexity. If you want to keep the current `s` behavior as well, you can map `s` to a table with `find`, `add`, and `delete` keys, which will allow you to specify different behavior depending on if you are `add`ing using the alias vs. `change`/`delete` using the alias.

**Comment by Kyuuhachi** [comment]
Actually it seems I don't need to do anything to keep the upstream behavior — `csss` happily replaces whatever delimiter is available with a space.

**Comment by kylechui** [comment]
Oh yeah, I suppose I did code aliases to take precedence 😄
