### ISSUE TITLE
Replay macro when `ys` was run with motion like `t` or `f`

### ISSUE THREAD

**Issue by dajoha** [kylechui/nvim-surround#263]
### Checklist

- [X] Have you tried updating the plugin to the latest version?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

### Neovim Version

NVIM v0.9.2

### Plugin Version

Tagged (Stable)

### Minimal Configuration

```lua
use {
  'kylechui/nvim-surround',
  config = function ()
    require('nvim-surround').setup {}
  end
}
```

### Sample Buffer

```
one,
two,
three,
```

### Keystroke Sequence

Record this macro on line 1 : `qa0yst,)`
Then replay it on line 2: `@a`

### Expected behavior

```
(one),
(two),
three,
```

### Actual behavior

```
(one),
<80><fd>atwo<80><fd>a,
three,
```
(Chars between `<` and `>` are special characters)

### Additional context

Motions which seem to be impacted are `t`, `f`, `T`, `F` (followed by any character).

After recording the macro: `:echo @a` shows `0yst,<80><fd>a)`, but running `:let @a = "0yst,)"` does not fix the problem.

**Comment by kylechui** [comment]
Notes:
- Able to replicate
- Seems to not cause issues with recording `ysiw)` or `ys$)` in the macro

Should probably try to figure out what `<80>` and `<fd>` refer to.

**Comment by dajoha** [comment]
It appears there is a similar problem with https://github.com/tpope/vim-surround, so maybe it's more a limitation of NeoVim and/or Vim than a bug from nvim-surround

**Comment by kylechui** [comment]
I see, so the keycode that's getting inputted is doing something like `K_SPECIAL -> KS_EXTRA -> KE_NOP`. This doesn't seem to happen with other custom operators like `gc` from Comment.nvim; I'm not sure if this is an upstream issue or something that both `(n)?vim-surround` happened to mess up.

**Comment by zdcthomas** [comment]
I'm seeing this issue as well, is there any progress on understanding or any fixes anyone has found? I haven't dug much into myself but I'd like to

**Comment by kylechui** [comment]
I personally haven't looked into it since the last message; if you do find anything please share 👀

**Comment by kylechui** [comment]
Hmm it seems related to this [upstream issue](https://github.com/neovim/neovim/issues/25865) (I was able to recreate the issue by running `qa0yst,)` and then `:put a`), but I'm not sure what the solution here would be.

**Comment by kylechui** [comment]
It seems like this issue has just magically disappeared for me on v0.10.0? Can anyone do me a favor and double-check?

**Comment by zdcthomas** [comment]
I was about to say the same thing (honestly kinda spooky I was just about to comment, haha)

**Comment by kylechui** [comment]
I was procrastinating on doing my homework so I just figured I'd go back through all the issues and check in :laughing: I'll mark this as resolved but anyone can feel free to ping me if anything changes
