### ISSUE TITLE
On Highlight Functionality or Disable Cursor Line

### ISSUE THREAD

**Issue by NotNullBool** [kylechui/nvim-surround#265]
**Checklist**
- [x] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

**Is your feature request related to a problem? Please describe.**
If possible, provide a sample buffer/keymap sequence, along with the expected result.

On highlight function feature.

**Describe the solution you'd like**

I want to either have a way to be able to disable the column line and cursor line highlight or to have a function called when highlight is active.

So this can be more consistant to visual mode since I cant see the highlight because of my cursor line being too bright.

**Comment by NotNullBool** [comment]
[I went ahead and forked it for the time being :)](https://github.com/NotNullBool/nvim-surround)

**Comment by kylechui** [comment]
I imagine you could do something like this, which wouldn't require any modification to the plugin itself:
```lua
require("nvim-surround").setup({
    keymaps = {
        ys = "false",
    },
})
vim.keymap.set("n", "ys", function()
    -- Disable highlights here
    require("nvim-surround").normal_surround()
    -- Re-enable highlights here
end)
```

**Comment by kylechui** [comment]
@NotNullBool Have you taken a look at `NvimSurroundHighlight`? I personally use:
```lua
vim.cmd.highlight("default link NvimSurroundHighlight Todo")
```
to make the highlights more visible.

**Comment by NotNullBool** [comment]
Yeah I thought about that but I wanted similar functionality to visual mode since that disables cursor line and cursor column temporarily

**Comment by kylechui** [comment]
Ah I see; that isn't exactly "intentional" behavior since the highlights just get auto-disabled whenever you enter visual mode. Maybe I'll add some callback function that takes in a `selection` and is called everytime some highlight event occurs, but I'm not sure yet.

**Comment by NotNullBool** [comment]
Thanks for hearing me out I really appreciate it! :)

**Comment by kylechui** [comment]
I think managing the highlights is not a key concern for this plugin, so I'll probably pass on implementing it "upstream". Your fork seems relatively simple and works, so I would suggest you keep that.
