### ISSUE TITLE
When using functions to return surroundings, surroundings are not cached for subsequent dot-repeat invocations

### ISSUE THREAD

**Issue by andrewferrier** [kylechui/nvim-surround#27]
As discussed in https://github.com/kylechui/nvim-surround/issues/5#issuecomment-1178773015.

I think the way *I* would prefer this to behave would be that when I do a surround add, the values returned by the custom functions for the surroundings (which in the case of the built-in examples for `i` and `f` use `vim.fn.input`) are cached, so that when a dot-repeat is used, those same values are used again - until surround add is performed again in a non-dot-repeat context.

For me, this is really the whole value of those `f`/`i` style mappings, because dot-repeat can be used to add the same surroundings in many places rapidly.

I cannot think of a usecase for changing them each time (otherwise this isn't really easier than just navigating to the right place and adding text directly without using surround), so I think caching them would be safe, personally.

**Comment by andrewferrier** [comment]
By the way, as  general comment, you're doing a fab job working on this plugin and making it a really good NeoVim equivalent to surround/sandwich - even exceeding capabilities in many places! Thanks for all your hard work.

**Comment by andrewferrier** [comment]
Just an additional thought - there might be legitimate reasons not to cache the result in some cases. For example, I could imagine `nvim-surround` supporting this:

["x"] = function(the_text_being_surrounded)
  return {
    // some clever mechanism to determine the left surround based on the_text_being_surrounded,
    // some clever mechanism to determine the right surround based on the_text_being_surrounded,
  }
end

Even though `nvim-surround` doesn't support that today (because it doesn't pass in the text being surrounded - although that would be a really interesting enhancement which would open up possibilities like the one above, happy to open an issue if you want), it might be good to keep that option open for future.

So what you *could* do is `true|false` flag on a per-pair basis (maybe refactor the table to support named options?) that determines whether to cache the result. Like this:

            ["i"] = function()
                return {
                    left = require("nvim-surround.utils").get_input(
                        "Enter the left delimiter: "
                    ),
                    right = require("nvim-surround.utils").get_input(
                        "Enter the right delimiter: "
                    ),
                    cache = true
                }
            end,

Just a thought...

**Comment by kylechui** [comment]
I really like these ideas! I think being able to pass the "text to be surrounded" as a parameter into the function call to help determine what the left/right pair should be is a very cool feature, even though I can't think of a proper use for it at the moment haha. As for caching, I think it's probably best for me to first implement *any* form of caching for these complex function calls, and then sort out "optional caching" from there, although I will keep that in mind!

**Comment by andrewferrier** [comment]
(FYI - if you did want to make the object returned from the function support additional attributes such as `cache`, it's relatively easy to check if the table is a list for backwards-compat reasons: `vim.tbl_islist()`)

**Comment by andrewferrier** [comment]
OK, I've opened another issue for the "pass in text to be surrounded" concept: https://github.com/kylechui/nvim-surround/issues/29.

**Comment by kylechui** [comment]
Do you think caching or passing in the text would be a more valuable feature to have? Just asking so I can decide which one to start working on first

**Comment by andrewferrier** [comment]
Personally I think the caching is more important - it means that surrounding with `i`/`f` is more useful...

**Comment by kylechui** [comment]
@andrewferrier The newest branch `cache-function-inserts` should be good for testing; a warning that it might be a bit buggier than usual since I shifted some things around internally.

**Comment by kylechui** [comment]
After some testing on my end, I think it's good to go; I want to get back to figuring out how to properly automate testing using plenary, instead of doing this sort of weird "guessing" if the plugin fails or not.

**Comment by andrewferrier** [comment]
> After some testing on my end, I think it's good to go; I want to get back to figuring out how to properly automate testing using plenary, instead of doing this sort of weird "guessing" if the plugin fails or not.

Cool! It seems to work for me right now but agree automated tests is probably a good focus to make the plugin as robust as possible...
