### ISSUE TITLE
Cannot create custom surround pairs with multibyte-characters

### ISSUE THREAD

**Issue by Mango0x45** [kylechui/nvim-surround#271]
### Checklist

- [X] Have you tried updating the plugin to the latest version?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

### Neovim Version

v0.9.4

### Plugin Version

Tagged (Stable)

### Minimal Configuration

```lua
require('nvim-surround').setup {
    surrounds = {
        ['’'] = {
            add = { '‘', '’' },
        }
    }
}
```

### Sample Buffer

```
fo*o
```

(`*` is the cursor)

### Keystroke Sequence

```
ysiw’
```

### Expected behavior

```
‘foo’
```

### Actual behavior

```
’foo’
```

### Additional context

In case the GitHub font makes it hard to see, I am trying to create a custom surround pair using unicode curly quotes, which I have on my keyboard.  I expect to be able to surround things with an opening curly quote and a closing curly quote, but the plugin completely ignores my configuration and just uses the closing quote on both ends.  If I change the config to be `['X'] = { add = … } }` where X is any regular ASCII character, this issue stops.

**Comment by Mango0x45** [comment]
Update: Did a little testing, the issue seems to not be for all multi-byte characters? Doing `['ß'] = …` works just fine, as does `['ẞ'] = …`.

**Comment by Mango0x45** [comment]
Neovim does indeed register it properly.

**Comment by Mango0x45** [comment]
Ok so it seems to also not work with the multi-byte ‘`…`’ character.  Could it be an issue with punctuation?  Lol

**Comment by kylechui** [comment]
I'm not sure; I don't have any special code to handle retrieving the character. Under the hood, things just use `vim.fn.getcharstr`.

**Comment by Mango0x45** [comment]
Well I’m playing around with `:lua print(vim.fn.getcharstr())` and seem to have absolutely no problems with inputting other unicode characters. What is the relevant part of the code? Maybe I can poke around and see if I can get something to work.

**Comment by kylechui** [comment]
I imagine the relevant code should be in `input.lua`.

**Comment by Mango0x45** [comment]
Ah here is a hint. At the very start of `M.get_add()` in `config.lua` I threw in:

```lua
for k, _ in pairs(M.get_opts().surrounds) do
    print(k)
done
```

and I noticed that while all the other keys are being stored correctly (along with `invalid_key_behavior` and some defaults), the `U+2019` quote mark that I entered is showing up not as it usually does as a right-single-quote, but as `<e2><80><fe>X<99>`. Looks like somewhere in the configuration unicode is not being properly handled.

**Comment by Mango0x45** [comment]
Looks like the issue occurs somewhere in the call to `M.translate_opts()` in `M.merge_opts()` in config.lua

**Comment by kylechui** [comment]
Sorry for the delay; just writing to let you know that I really appreciate the PR and that it will be merged soon:tm:; I just want to figure out how to get your change autopublished to LuaRocks as well so it might take a little bit.

**Comment by Mango0x45** [comment]
No worries! I just hope this gets merged soon™ because I use multibyte characters all the time :)
