### ISSUE TITLE
multi-character aliases

### ISSUE THREAD

**Issue by mscott99** [kylechui/nvim-surround#272]
**Checklist**
- [x ] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

**Is your feature request related to a problem? Please describe.**
If possible, provide a sample buffer/keymap sequence, along with the expected result.

I would like to add some surrounds which have a multi-character key, is this possible at the moment? I am trying to copy the "m(" surround from vim-sandwich which gives "\\left(" "\\right)". For this it is convenient to label the surround with an "m" prefix, though that seems to trigger a surround with a character "m" at the moment.
**Describe the solution you'd like**

A way to have multi-character surround keys, or aliases. Or a pointer to somewhere if a solution exists.

**Comment by kylechui** [comment]
Multi-character surrounds are not supported, nor are they expected to be supported in the near future. See #232

**Comment by mscott99** [comment]
Ah okay thanks.
