### ISSUE TITLE
Close matching paren enterd in search input

### ISSUE THREAD

**Issue by esumerfd** [kylechui/nvim-surround#274]
### Checklist

- [X] Have you tried updating the plugin to the latest version?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

### Neovim Version

: nvim -v
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.9.1/share/nvim"

Run :checkhealth for more info

### Plugin Version

Tagged (Stable)

### Minimal Configuration

require("nvim-surround").setup()

### Sample Buffer

Empty search input buffer

### Keystroke Sequence

/Foo(

### Expected behavior

/Foo(

### Actual behavior

/Foo()

### Additional context

To search for a method I need to enter /Foo(<RIGHT><BS> to search for unmatched string

**Comment by kylechui** [comment]
Wrong plugin, you probably have some `autopairs`-style plugin installed that's autocompleting the end brace.
