### ISSUE TITLE
Respect visual range on change surrounding pair

### ISSUE THREAD

**Issue by afonsocarlos** [kylechui/nvim-surround#277]
**Checklist**
- [x] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

**Is your feature request related to a problem? Please describe.**
Changing surrounding pairs inside a visual range performs changes outside of the range. I think changes should stick within the range.
Example issue:
```js
const names = [
   |'Jane',
    "John",
    "Mario",
    "Mary",
];

const roles = [
    "admin",
    "client",
    "maintainer",
];
```
Selecting within braces in array `names`: `vi[` 
Then changing items inside array: `:'<,'>norm cs"'`
Actually changes all quotes from `names` and one from `roles` (because the first item in `names` doesn't match the `cs"'`)

**Describe the solution you'd like**
I think the change actions should be performed only inside the `'<,'>` range if it's provided.

**Comment by kylechui** [comment]
I don't think this is feasible, as the command you gave as an example translates to "run the `cs` command once for each line in the visual selection". Why do you need to restrict your change to a selection? I feel like you might as well move your cursor to the right spot and then `cs`.

**Comment by kylechui** [comment]
Hey there, I wasn't able to replicate this on my system. By default the `a"` text object only "searches" on the current line for a surrounding pair; do you have `targets.vim` or `mini.ai` (or similar) installed?

**Comment by afonsocarlos** [comment]
Hi, thank you for your reply. Hmmm yes, I have `targets.vim` installed and it seems that's what's causing the problem! Removing it solved the issue :sweat_smile: thanks a lot for the help. I'll close the issue.
