### ISSUE TITLE
Highlight the visual selection when surrounding in visual selection / range

### ISSUE THREAD

**Issue by asmodeus812** [kylechui/nvim-surround#278]
When we have selected a visual block, and we press the binding for `visual`, the visual selection highlight is lost, i would expect the nvim surround highlight group to be applied on the last visually selected range, and maybe have <esc> cancel the operation (and the highlight) altogether. Reason being, at the moment there is no way to tell that we are in surround 'mode' after initiating surround with the `visual` keybind.

**Comment by kylechui** [comment]
Hi @asmodeus812 is this still an issue? For me the highlight persists after hitting `S`.

Related: #299 #312 #315

**Comment by kylechui** [comment]
Actually I'll close this in favor of the other issue, since it has a bit more information for me to work with; feel free to add any comments there.
