### ISSUE TITLE
`csbq` replaces with double quote

### ISSUE THREAD

**Issue by kuator** [kylechui/nvim-surround#284]
**Checklist**
**Have you read through `:h nvim-surround` to see if there might be any relevant information there?**
Yes

**Is your feature request related to a problem? Please describe.**
When I try to `csbq` this piece of text `(abc)`, it turns into `qabcq`, but  `"abc"` would be more preferrable, imo

**Describe the solution you'd like**
Would it be possible to add an option that makes `csbq` replace previous surrounding with double quote, as double quotes are what I use 99.9 percent of the time?

**Comment by kylechui** [comment]
You should be able to add a surround like `q = { add = { '"', '"' } }` for that behavior. Aliases for multiple characters don't have a well-defined "default" operation; someone else might prefer `'` normally or even `` ` `` by default.

**Comment by kuator** [comment]
Yes, what I was trying to ask is if it's possible for me to change the nvim-surround config in a way that `q` acts as an alias when I am trying to delete ``` or `'` or `"` with `dsq`, but when I try to change some other surrounding like `(` or `[` with `cs(q`, `cs[q`, `q`  acts as a double quote.

**Comment by kuator** [comment]
Thank you!
