### ISSUE TITLE
Dot repeat doesn't work with visual surround

### ISSUE THREAD

**Issue by janpeterd** [kylechui/nvim-surround#307]
### Checklist

- [X] Have you tried updating the plugin to the latest version?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

### Neovim Version

`NVIM v0.9.5`

### Plugin Version

Tagged (Stable)

### Minimal Configuration

```lua
{
    "kylechui/nvim-surround",
    version = "*",
    event   = "VeryLazy",
    config  = function()
        require("nvim-surround").setup()
    end,
}
```

### Sample Buffer

- `|` represent visual selection start and end

```
|Lorem| ipsum dolor
```
Select the word Lorem using `ve` then I press `S)` and the word is correctly surrounded.
Now I want to do the same for the next word, so move to the next word word using `W` and press `.` to try to repeat the last surround action.
```
(Lorem) |ipsum dolor
```
Now vim doesn't surround the selected word, but repeats some previous action that happened in the past. In my case it resulted in.
```
(Lorem)
```

### Keystroke Sequence

Keystrokes to select and surround first word: `veS)`
Keystrokes to move to next word: `W`
Keystrokes try repeat: `.`

### Expected behavior

Expected behavior would be that the word from the cursor to the end (`e`-motion) are surrounded by brackets.

### Actual behavior

The surround is not repeated and vim repeats another motion.

### Additional context

`verbose xmap S` returns this:
```
x  S           * <Plug>(nvim-surround-visual)                                                                                                                                [5/5]
                 Add a surrounding pair around a visual selection
        Last set from Lua
```

**Comment by kylechui** [comment]
Dot-repeat does not work with visual motions because only the start/end coordinates of a visual selection are saved; this means that the *semantics* of what you wished to surround aren't saved. In this case, you should be using a normal surround like `yse)` or `ysiw)` to maintain dot-repeat capabilities.
