### ISSUE TITLE
Mark fields of `user_options` as optional

### ISSUE THREAD

**Issue by gregorias** [kylechui/nvim-surround#313]
### Checklist

- [X] Have you tried updating the plugin to the latest version?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

### Neovim Version

0.9.5

### Plugin Version

Tagged (Stable)

### Minimal Configuration

N/A

### Sample Buffer

N/A

### Keystroke Sequence

N/A

### Expected behavior

Providing just the `surrounds` field to `buffer_setup` should type check.

### Actual behavior

Providing just the `surrounds` field to `buffer_setup` triggers a warning diagnostic from LuaLS.

![image](https://github.com/kylechui/nvim-surround/assets/722385/d67bb50c-76f7-4bdc-9a33-3bc80ef4df79)

### Additional context

The `user_options` annotations is at https://github.com/kylechui/nvim-surround/blob/84a26afce16cffa7e3322cfa80a42cddf60616eb/lua/nvim-surround/annotations.lua#L56. Could you either mark fields as optional (with a question mark) or change the type annotation of `buffer_setup`?

**Comment by kylechui** [comment]
Seems related to #305 ?

**Comment by gregorias** [comment]
Indeed, it’s a duplicate.

**Comment by kylechui** [comment]
Do you mind checking out the PR and seeing if the question marks are in the right place?

**Comment by gregorias** [comment]
I checked it. Looks good.
