### ISSUE TITLE
Changing multi-byte surrounds doesn’t work

### ISSUE THREAD

**Issue by Mango0x45** [kylechui/nvim-surround#317]
### Checklist

- [X] Have you tried updating the plugin to the latest version?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

### Neovim Version

`NVIM v0.9.5`

### Plugin Version

Tagged (Stable)

### Minimal Configuration

```lua
require('nvim-surround').setup {
	surrounds = {
		['’'] = {
			add = { '‘', '’' },
			find = '‘[^‘’]*’',
		}
	}
}
```

### Sample Buffer

`‘foo *bar’`

`*` is the cursor position

### Keystroke Sequence

`cs’_`

### Expected behavior

`_foo bar_`

### Actual behavior

`_<80><98>foo bar<e2><80>_`

### Additional context

The above broken example uses U+2018 LEFT SINGLE QUOTATION MARK and U+2019 RIGHT SINGLE QUOTATION MARK.

This is most likely related to the same issue that was fixed by this pr: https://github.com/kylechui/nvim-surround/pull/273

**Comment by kylechui** [comment]
Yeah I did some debugging and it seems to be coming as a result of the default `invalid_key_behavior.delete` matching just the first and last bytes of the quote characters, instead of the entire character. I'll see what I can do about it.

**Comment by kylechui** [comment]
Can you try out #318 and see if it fixes the issue? I added a few test cases but I'd like some manual testing just in case :)

**Comment by Mango0x45** [comment]
I’ll try it out later today

**Comment by kylechui** [comment]
You should be able to just pull in the latest tag on `main` now; thanks for reporting the bug!
