### ISSUE TITLE
Remove HTML special case

### ISSUE THREAD

**Issue by andrewferrier** [kylechui/nvim-surround#32]
This may have already occurred to you, but I think you could now remove the explicit HTML support in the config and refactor it as a (default) pair that uses function and input to get the tag.

This'll probably simplify some code.

**Comment by andrewferrier** [comment]
Maybe not actually - I saw you do some fancy stuff with HTML attributes during replacement. OK, ignore this...

**Comment by kylechui** [comment]
As I mentioned [here](https://github.com/kylechui/nvim-surround/issues/5#issuecomment-1178263896), refactoring would only really allow for *inserting* HTML tags using a function, but not changing/deleting.
