### ISSUE TITLE
Bug: Manual lazy loading failes

### ISSUE THREAD

**Issue by ranjithshegde** [kylechui/nvim-surround#34]
This is my packer config for surround:
```lua
use {
    "kylechui/nvim-surround",
    opt = true,
    config = function()
        require("nvim-surround").setup {}
    end,
}
```

I either load the plugin manually `require("packer").loader("nvim-surround")` or `:PackerLoad nvim-surround`

When I try any keybinding pertaining to surround like `cs"` or `ysap"`, this error is thrown

```
E5108: Error executing lua ...ack/packer/opt/nvim-surround/lua/nvim-surround/utils.lua:32: attempt to index field 'buffer_opts' (a nil value)
stack traceback:
        ...ack/packer/opt/nvim-surround/lua/nvim-surround/utils.lua:32: in function 'is_HTML'
        ...pack/packer/opt/nvim-surround/lua/nvim-surround/init.lua:187: in function <...pack/packer/opt/nvim-surround/lua/nvim-surround/init.lua:178>
```

This is a new problem that started after the `buffer_local` feature was added

**Comment by kylechui** [comment]
@ranjithshegde Please try out the new `fix-lazy-loading` branch; the issue was that my autocommand for setting up the plugin was only being run on the `BufEnter` event, so I added another line to set up the plugin when `require("nvim-surround").setup()` is called (i.e., when the plugin is loaded in).

**Comment by ranjithshegde** [comment]
> @ranjithshegde Please try out the new `fix-lazy-loading` branch; the issue was that my autocommand for setting up the plugin was only being run on the `BufEnter` event, so I added another line to set up the plugin when `require("nvim-surround").setup()` is called (i.e., when the plugin is loaded in).

It did smell like a non-triggered au-event to me. Sorry for not mentioning it in my bug report. I am too cluttered due to a thesis deadline.



> Edit: Please let me know if this fix works for you, and I'll merge it into main

Just tested it! works fine. Thank you so much for the fix

**Comment by kylechui** [comment]
No worries, thanks for taking the time to open up the issue to begin with, and good luck with your thesis!
