### ISSUE TITLE
BUG: Unreliable behaviour for "change" action

### ISSUE THREAD

**Issue by Kyren223** [kylechui/nvim-surround#345]
### Checklist

- [X] Have you tried updating the plugin to the latest version?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

### Neovim Version

v0.10.0

### Plugin Version

Tagged (Stable)

### Minimal Configuration

    {
        'kylechui/nvim-surround',
        version = '*',
        lazy = false, -- just so it loads immediately
        opts = {
            keymaps = {
                change = 'cs',
            },
        },
        keys = {' },
            { 'cS', '<Plug>(nvim-surround-change)' },},
        },
    },

### Sample Buffer

            { 'cS', '<Plug>(nvim-surr|ound-change)' },
| is cursor

### Keystroke Sequence

cS({

### Expected behavior

            { 'cS', '<Plug>{ nvim-surround-change }' },

### Actual behavior

            { 'cS', '<Plug>{
nvim-surround-change
}' },

### Additional context

when using the default keymap `cs` it does "visual" and not "visual line" but when using the plug it does visual line even though it's `change` and not `change-line`, weirdly enough, even if I remove all the keys and just use keymaps but change cs in keymaps to cS, then it again does visual line.
**this seems to be only with cS, when trying something like cW, it seems to work correctly**

**Comment by kylechui** [comment]
You need to set `change_line = false`, as otherwise there's some race condition for setting the cS keymap.

**Comment by Kyren223** [comment]
Is there a way to disable all the default keymaps, or do I need to set each of them to false?

**Comment by kylechui** [comment]
Unfortunately, you'll need to set all of them to `false` yourself.

**Comment by Kyren223** [comment]
Alright thanks, do I close this issue or keep it open to add a `enable_default_keymaps` options?

**Comment by kylechui** [comment]
I think it's fine to close it for now. Adding a `enable_default_keymaps` option would IMO cause more confusion (i.e. if `enable_default_keymaps = true` but the user overrides them in the setup call).
