### ISSUE TITLE
Using a keybinding as an alias

### ISSUE THREAD

**Issue by oiiiiiiii** [kylechui/nvim-surround#351]
**Checklist**
- [x] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

**Is your feature request related to a problem? Please describe.**
I want to add a new alias that is not just one character, but instead a keybinding (in my case `<A-.>`. I tried the following setup (lazy), but it doesn't work:

```
return {
    "kylechui/nvim-surround",
    version = "*", -- Use for stability; omit to use `main` branch for the latest features
    event = "VeryLazy",
    config = function()
        require("nvim-surround").setup({
            aliases = {
                ["<A-.>"] = ")"
            }
        })
    end
}
```
When I replace the keybinding with a single character (e.g. `d`), it works fine. But I would like this as a keybinding, as I mapped that to ")" everywhere else.

**Describe the solution you'd like**
Being able to not only map single characters for an alias, but instead keybindings (if that is possible).

**Additional context**
None

**Comment by oiiiiiiii** [comment]
I also tried mapping `<A-.>` to `)` in every vim mode there is, but this doesn't work.

**Comment by kylechui** [comment]
Sorry for the (really) late response, fixed in [the latest commit](https://github.com/kylechui/nvim-surround/commit/d66b6a206f269e46637f16315d2defc35fc3647e)/[version](https://github.com/kylechui/nvim-surround/commit/d66b6a206f269e46637f16315d2defc35fc3647e).

**Comment by oiiiiiiii** [comment]
Thanks a lot! :)
