### ISSUE TITLE
Add an option such that 'da}' can delete the ```,``` following ```}```.

### ISSUE THREAD

**Issue by gaoqiangks** [kylechui/nvim-surround#353]
**Checklist**
- [ ] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

**Is your feature request related to a problem? Please describe.**

This is mainly related to json files. For example, in a setting file in json, things may look like 

```
{
    abc
},
{
    def
},
{
    ghi
},

```

In this case, if I want to delete the entry ```abc```, I centainly want to delete the whole block, and the following ```,```.

**Describe the solution you'd like**

When the cursor is on ```abc```, ```da}``` will delete the whole block and the following ```,```.

**Additional context**

**Comment by kylechui** [comment]
You can try this configuration; feel free to re-open if there's some issue with it:
```
require("nvim-surround").setup({
    surrounds = {
        ["}"] = {
            find = "%b{},?",
            delete = "^({)().-(},?)()$",
        },
    },
})
```
