### ISSUE TITLE
E475: Invalid argument: exactly one of {chunk} or {range} required

### ISSUE THREAD

**Issue by nicwest** [kylechui/nvim-surround#356]
### Checklist

- [X] Have you tried updating the plugin to the latest version?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

### Neovim Version

NVIM v0.10.0-dev

### Plugin Version

Tagged (Stable)

### Minimal Configuration

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
      {
          "kylechui/nvim-surround",
          version = "*", -- Use for stability; omit to use `main` branch for the latest features
          event = "VeryLazy",
          config = function()
              require("nvim-surround").setup()
          end,
      }
})
```

### Sample Buffer

hello world!

### Keystroke Sequence

^fwviwS"

### Expected behavior

hello "world"!

### Actual behavior

hello world!

### Additional context

I get the following error: `E475: Invalid argument: exactly one of {chunk} or {range} required`

**Comment by kylechui** [comment]
I copied your minimal configuration into a `minimal_init.lua`, then ran `nvim -u minimal_init.lua` and was unable to reproduce the issue. Could you try updating to a stable version of Neovim and see if that resolves the issue (although it really shouldn't matter much).

**Comment by nicwest** [comment]
upgrading to stable version of neovim fixed the issues for me, thanks!

```shell
nvim --version
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info```
