### ISSUE TITLE
Add \begin{}...\end{} when surrounding in a .tex file

### ISSUE THREAD

**Issue by MMachado05** [kylechui/nvim-surround#358]
**Checklist**
- [x] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

**Is your feature request related to a problem? Please describe.**
When using vim-surround, I was able to visual-line select some piece of a LaTeX file, and pressing `\` would automatically open a `\begin{` in my command line. When I finished the environment, the complement pair would automatically be set as `\end{...}`. Currently, with `nvim-surround`, pressing `\` simply immediately creates a surrounding with those empty backslashes.

**Describe the solution you'd like**
I'd like `nvim-surround` to treat backslashes in .tex files as denoting an environment, just as in `vim-surround`.

**Additional context**
N/A

**Comment by kylechui** [comment]
I don't plan on having filetype-specific configurarions set up for the user by default; perhaps VimTeX or [this post](https://www.github.com/kylechui/nvim-surround/discussions/53#discussioncomment-3142459) would be of use to you.

**Comment by MMachado05** [comment]
Holy moly, that post showed me some really cool stuff I'd never seen before! Thanks for the link; this feature being unplanned now makes a lot of sense considering the extensibility of your plugin. Thank you for the hard work!

**Comment by gaoqiangks** [comment]
vimtex already has this feature, use `dae` to delete an environment.
