### ISSUE TITLE
Highlight region being surrounded

### ISSUE THREAD

**Issue by andrewferrier** [kylechui/nvim-surround#4]
Firstly, let me just say thank you for taking the initiative to write a surround plugin for NeoVim. This is sorely needed and you've made a great start. I'm coming from vim-sandwich (the main VimL competitor to vim-surround) which has a few features that vim-surround doesn't, so I'm just going to put some of them out here in issues...

One thing that would be really nice to see is that when the insert keymaps is pressed, and then a text object is entered, but just before the pair keystroke is typed, the area to be affected is highlighted, similar to how `require("vim.highlight").on_yank` works, except that it's persistent until the pair keystroke is typed. This just acts as a visual confirmation of the area affected, and it's how vim-sandwich works. It could be optional if it's something you think some folks won't like.

**Comment by andrewferrier** [comment]
More info on how vim-sandwich does it here: https://github.com/machakann/vim-sandwich/blob/e114a5e0c90aefed3d2a48ca326eff9d39bc90a9/doc/operator-sandwich.txt#L920

**Comment by kylechui** [comment]
Thanks for the encouraging words! That does seem like it would be quite a nice "quality of life" feature; I'll add that to the list of things to work on (but it'll probably have to wait until I iron out more of the bugs in the code, as well as add dot-repeating).

**Comment by andrewferrier** [comment]
Sure, makes sense; it is definitely an enhancement, not a requirement. Thanks.

**Comment by kylechui** [comment]
@andrewferrier I had some spare time on my hands, so I tried implementing this on [highlight-selection](https://github.com/kylechui/nvim-surround/tree/highlight-selection), let me know if this is close to what you imagined for this feature :)

**Comment by andrewferrier** [comment]
This is very good, thank you! This is almost exactly what I had envisaged. A few minor suggestions:

* `vim-sandwich` at least makes the highlight flash time configurable. I'm happy with what you have by default, but that's something to consider...
* You probably want to document the `HighlightTextObject` highlight in case somewants to override / configure it.

When testing this, though, I did discover bug #16. I'm not sure if the two are related (I don't think they are, as #16 shows up even on the `main` branch); just something to be aware of.

**Comment by kylechui** [comment]
@andrewferrier I just pushed a change to the same branch that defines a new parameter in the default setup table (more info can be found in `:h nvim-surround.highlight_motion`), please let me know what you think.

Note to self: Update the README before merging if the commit is good to go

**Comment by antenore** [comment]
@kylechui You are amazingly fast!!! Thank you!!! Please consider enabling some sort of donations, with or without the GitHub sponsorship integration.

**Comment by kylechui** [comment]
@antenore Thanks for the kind words! I'm extremely flattered---I've just applied for the GitHub sponsorships program, so you might see that pop up on my page in the upcoming weeks (whenever that gets verified)
