### ISSUE TITLE
Tab interferes with nvim-surround

### ISSUE THREAD

**Issue by jemag** [kylechui/nvim-surround#44]
Test case:
```lua
fun (
	"test"
	"test"
	"test"
)
```
Where the space before each "test" is an actual tab character, e.g.:
![image](https://user-images.githubusercontent.com/7985687/178181303-b71912ac-18b2-4a59-b03b-499b1b8d2bce.png)

Hit `cs"'`

Notice it does not do anything. Works with spaces before each `"test"` however.

**Comment by kylechui** [comment]
@jemag Please test the branch `fix-tabs` branch that I've just created to see if that fixes your issue.

**Comment by jemag** [comment]
@jemag hey, sorry I was creating these issues quick before going to bed, I will definitely take a look tomorrow though. Thanks for the quick work

**Comment by kylechui** [comment]
No worries, I'll just merge them into main then if they're working on my end. Should really look into how such basic bugs cropped up all of a sudden.

**Comment by kylechui** [comment]
By the way, thanks for opening up these issues! It really does help make the plugin more stable for more people
