### ISSUE TITLE
changing surround pair changes indentation

### ISSUE THREAD

**Issue by jemag** [kylechui/nvim-surround#46]
Test case:
```lua
fun (
  "test"
  "test"
  "test"
  "test"
  "test"
)
```
with spaces before each "test". Hitting `cs"'` inside the `"` of the first `test` will result in the following change in indentation:
```lua
fun (
    'test'
    "test"
    "test"
  "test"
  "test"
)
```
Similarly, doing it on the last `test` will result in : 
```lua
fun (
  "test"
  "test"
  "test"
  "test"
  'test'
  )

```

**Comment by kylechui** [comment]
@jemag Just as a question, were you in any particular file type when this bug occurred? Or just in a scratch buffer?

**Comment by jemag** [comment]
@kylechui just a normal `.txt` file that I created for testing. It doesn't change the indention anymore since the fix was merged.
