### ISSUE TITLE
Dot-repeat without re-input of delimiters?

### ISSUE THREAD

**Issue by Invertisment** [kylechui/nvim-surround#48]
Hey.
I use Spacemacs and surrounding of text is implemented by remembering the inputs as well as the surrounding keys.
What this means is that when I click `yse$` then it would surround my word like this: `$hello$` and then I could repeat it without inputting `$` character.

Basic case:

The repeating breaks when I use `.` to repeat my motion:
```
[CURSOR]hello
hello
```
Press `yse$`. Then go to next line (`j0`) and then press `.`.
It asks to enter the character `$` which I already entered :shrug: 

Slightly harder case:

I could then make a macro and I would like to surround the word "world" in `$`:
```
[CURSOR]hello world
hello1 world
hello12 world
hello123 world
hello1345 world
```
Press `qqyse$j` and then press `4@q`. 
This is the result on Spacemacs:
```
$hello$ world
$hello1$ world
$hello12$ world
$hello123$ world
$hello1345$ world
```
And the result on `nvim`... well it jumps somewhere instead of doing what I expected.

**Comment by kylechui** [comment]
Hey there, I wasn't quite able to reproduce your issue---I tried both `yse$` and `ysiw$`, both of which are able to be dot-repeated without needing to re-enter `$`. Are you using the latest commit on the `main` branch?

**Comment by Invertisment** [comment]
I may probably be using the older version. Maybe my plugin installer didn't upgrade it yet and it's a non-issue.
Yes, the macro misses `q` at the end to stop the recorder.

**Comment by kylechui** [comment]
If you're using `packer.nvim` to manage your plugins you can run `:PackerUpdate nvim-surround`.

**Comment by Invertisment** [comment]
I use Plug. and `:PlugUpgrade` fixed it.
The plug-in works as expected. Repeats work and macros work. Very nice. Thanks for the plug-in!
