### ISSUE TITLE
Provide "function" pair

### ISSUE THREAD

**Issue by andrewferrier** [kylechui/nvim-surround#5]
One feature that vim-sandwich has that's very useful is a special case... if you type `f` for the surround key (when adding at least), it prompts for the name of a function, then surrounds with `functionname(` on one side and `)` on the other. Sounds trivial, but I end up using it all the time. Would be nice to see this in nvim-surround.

**Comment by sQVe** [comment]
@kylechui `vim-sandwich` also has `i` which is helpful. It allows you to manual input the head and the tail, separately. Very useful in some cases. Would be great iif that was included also.

**Comment by kylechui** [comment]
Hey all, I'm going to try and implement this feature next, please checkout the new branch `add-custom-inputs` (should be in the sidebar), which adds basic support for custom input types:
```lua
require("nvim-surround").setup({
    delimiters = {
        pairs = {
            i = {
                function()
                    return require("nvim-surround.utils").get_input("left: ")
                end,
                function()
                    return require("nvim-surround.utils").get_input("right: ")
                end,
            },
        }
    }
})
```
The above config sets up the keybind that @sQVe wanted, and I'm pretty sure that something similar can be done for @andrewferrier's idea as well. The idea is that you just need to provide an anonymous function with the desired return value for each of the left, right delimiters.

**Comment by kylechui** [comment]
If these commits work well for the two of you, I think I can delete all of the HTML-specific code in favor of this function-style mapping

**Comment by kylechui** [comment]
@akinsho The main problem I have right now with using `vim.ui.input` is that it *isn't* blocking, and would require a massive rewrite of a lot of the internals of the plugin in order to do all the processing in `vim.ui.input`'s callback function. That's why for the time being, I'm still sticking with `vim.fn.input`. See #17

On another note, I'm going to rewrite this new feature to have one function that returns a table with two values, as otherwise the user would need to input twice for HTML tags

**Comment by akinsho** [comment]
Fair enough, don't let that stop you as you say 👍🏿 

FWIW, if the substitution is in a function somewhere, presumably that function can be called inside another callback? I haven't really read any of the code, so I'm sure I'm oversimplifying massively.

**Comment by kylechui** [comment]
I decided to merge this first because I don't think the extra code is going to be prone to bugs/is that controversial, and also I want to start working on buffer-local mappings sooner :P

**Comment by kylechui** [comment]
@andrewferrier Yes, please open up a new issue---I actually don't know of an elegant way to accomplish it at the moment, but I'll try my hand at it once buffer-local mappings are merged into main
