### ISSUE TITLE
nvim-surround looks backwards for 'nearest' replacement even with separators on the current line

### ISSUE THREAD

**Issue by andrewferrier** [kylechui/nvim-surround#50]
**Checklist**
- [X] Have you updated the plugin to the latest version on `main` branch?
- yes, commit 1d5a09
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

**To Reproduce**
Buffer:

```
a = b(
     c.d("xyz")
)
```

Place cursor on c, type `c(`

**Expected behavior**
The braces surrounding `"xyz"` are highlighted ready for replacement

**Actual behavior**
The braces after `b` and on the standalone line are highlighted ready for replacement

**Explanation**
It seems to me that in general if `nvim-surround` is not *on* the replacements, it would want to look *forward* first - at least on the same line. I get that if it's inside the braces (which to be fair it is for the wider braces), that seems like the right ones to pick up, but I wonder if a special case for the current line would make sense?

**Comment by kylechui** [comment]
I was also thinking about this considering if your file is quite large, the surrounding braces might not even be on the screen. I might consider adding an option for this, but I'm pretty sure vim-surround would exhibit the same behavior

**Comment by andrewferrier** [comment]
Yeah, I just checked and you are correct - `vim-surround` does behave the same way (which doesn't mean that's the right way, but does at least mean you are consistent ;). I wouldn't object strongly if you closed this. In effect, what I'm asking for here would be a special case that could be confusing.

**Comment by kylechui** [comment]
@andrewferrier I think ideally I would want to open up a discussions thread for this, but I feel like nobody checks it :/ I wish polls would "notify" everybody that looks at this repo

**Comment by NoahTheDuke** [comment]
I would prefer to match how it works currently. When "inside" a pair of braces (of any kind), my expectation is that all actions will interact with them and not later braces I'm not currently inside. I might be biased because I work in a lisp (Clojure), but to me, interacting with the surrounding braces is the most important part of a "surround" plugin.

**Comment by kylechui** [comment]
@NoahTheDuke Indeed with so "controversial" a change as this one I would most definitely make it a user-defined option in settings, but in any case I'm leaning towards not implementing it at all for simplicity reasons

**Comment by kylechui** [comment]
Closing this as I don't intend on adding this to the plugin.
