### ISSUE TITLE
Provide some simple examples / instructions of how to use in the README

### ISSUE THREAD

**Issue by andrewferrier** [kylechui/nvim-surround#57]
**Checklist**
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

**Describe the solution you'd like**
I guess one of the things that would be great is to attract more folks to nvim-surround who aren't necessarily users of a surround plugin already.

I know that you have a demo video, but many folks (like me) really don't like watching videos (and minor bit of feedback - I think your video is a little fast to follow it on the first run through anyway). Also, I know you have comprehensive help in `:h nvim-surround` - which is great.

But looking at the README, the one thing I realized it was lacking is some introductory explanation of how to use the plugin. It jumps straight to configuration, but doesn't talk about some simple default usage, e.g. `daq` or `cr{[`. At the least, it would probably be helpful to have some examples, with "before" and "after" text, even if the README isn't a comprehensive reference.

What do you think?

**Comment by andrewferrier** [comment]
(For what it's worth, from what I've seen, the evolving convention seems to be that the README is for getting started/"selling" your plugin, and the help is for reference information).

**Comment by andrewferrier** [comment]
> > (For what it's worth, from what I've seen, the evolving convention seems to be that the README is for getting started/"selling" your plugin, and the help is for reference information).
> 
> Yeah I initially thought that most everybody that would even find this project would have already been using a surround plugin, but I'll add a `Usage` section to the README now. The original goal was to "trim the fluff" and keep the README as short as possible, thereby not wasting the user's time

Yeah, agreed, and I don't think it needs to be comprehensive (you could redirect to help for that); but a short set of examples I think would be helpful at a minimum.

**Comment by kylechui** [comment]
@andrewferrier Forgot I was on main... oops. Good news is I've written up short blurbs about add/delete/change, take a look and let me know what you think!

**Comment by andrewferrier** [comment]
Looks perfect!
