### ISSUE TITLE
Add support for `yS`

### ISSUE THREAD

**Issue by melkster** [kylechui/nvim-surround#62]
**Checklist**

- [x] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

**Is your feature request related to a problem? Please describe.**

vim-surround has the command `yS` which puts the surrounded text on its own line, as described [here](https://github.com/tpope/vim-surround/blob/master/doc/surround.txt#L66-L73):

> There is also `yS` and `ySS` which indent the surrounded text and place it
> on a line of its own.
>
> In visual mode, a simple `S` with an argument wraps the selection. This is
> referred to as the `vS` mapping, although ordinarily there will be
> additional keystrokes between the `v` and `S`. In linewise visual mode, the
> surroundings are placed on separate lines and indented. In blockwise visual
> mode, each line is surrounded.

**Comment by kylechui** [comment]
Going to merge this into #58.
