### ISSUE TITLE
Add config example for markdown links as shown in the video in README.md

### ISSUE THREAD

**Issue by kovasap** [kylechui/nvim-surround#64]
The `Sl` keybind that adds a markdown link in README.md doesn't work with a fresh install and I assume is a custom keybind.  Could the config that provides this be added to the README or linked to?  It was kinda a tease to see that cool feature and then not know how to make it work.

**Comment by kylechui** [comment]
Hi there, I haven't gotten around to it yet but I will link to #53 in the README at some point.

**Comment by kovasap** [comment]
Ok awesome!  This is exactly what I was looking for.

**Comment by kylechui** [comment]
Added to the README in the latest commit.

**Comment by kovasap** [comment]
Thanks!
