### ISSUE TITLE
[Testers needed] General refactor on new branch

### ISSUE THREAD

**Issue by kylechui** [kylechui/nvim-surround#65]
I've shifted around the code quite a bit on `refactor-code`, as well as introduced a bunch of comments that make use of Sumneko's type annotating system. I've been meaning to do this as a way to "prepare" for the (presumably large) changes that might crop up next week due to #60. It's already passed all of my automated tests, but I would appreciate it very much if people could test out this branch's stability with respect to their average workflows. I don't want to merge it into main just for it to break a bunch of things. Thanks everyone!

Edit: I'll be doing a review of all of the changes that I've made sometime tomorrow, to make sure that all of the changes that I've made to the code base have only changed the plumbing and none of the porcelain :)

## Known "breaking changes":
* When inserting a new character to surround, "ad-hoc" insertions as per #59 is *no longer the default* [intentional]
* `utils.get_input(prompt)` has been deprecated due to dependency loops; please use `vim.fn.input({ prompt = prompt })` instead

**Comment by kylechui** [comment]
On a semi-unrelated note: would it be preferred to have a discussion page or issue for breaking changes?

**Comment by kylechui** [comment]
@andrewferrier I've noted that this is a breaking change in the top-level comment of this issue thread

**Comment by andrewferrier** [comment]
> On a semi-unrelated note: would it be preferred to have a discussion page or issue for breaking changes?

I think an issue seems to be the evolving convention. NeoVim does that, null-ls does that, treesitter does that, and I'm pretty sure a few other plugins do that. It's easy to subscribe to.

Note also that I think another convention is to add a `!` to your conventional commits. e.g. `feat! Did some stuff that broke things`. I think that `packer.nvim` at least then highlights them specially.

**Comment by kylechui** [comment]
I've started basic work on the wiki, and have modeled it to have a similar feel to [telescope's wiki](https://github.com/nvim-telescope/telescope.nvim/wiki), but I'm unsure how to allow other people to contribute to it.

CC: @benfrain In case this is something you'd like to figure out/help with documenting?
