### ISSUE TITLE
Support add tag around selected tag

### ISSUE THREAD

**Issue by ShiChenCong** [kylechui/nvim-surround#70]
**Checklist**
- [x] Have you read through `:h nvim-surround` to see if there might be any relevant information there?
yes

**Describe the solution you'd like**
Thank you for then work ! 
![image](https://user-images.githubusercontent.com/22486446/178994906-9ed1857a-05c1-432c-ac0e-4aae120546a9.png)

Add tag around selected tag, like vim-surround, selected tag,press `S`,  then input tag, wil added to around div

**Comment by kylechui** [comment]
@ShiChenCong This should be possible via selecting the tag, then typing `St[tag contents]`, e.g. `Sth1 id="some string"`.

**Comment by ShiChenCong** [comment]
@kylechui Thank you, works!
