### ISSUE TITLE
Enhance deleting of HTML tags, similar to vim-surround

### ISSUE THREAD

**Issue by rorj** [kylechui/nvim-surround#76]
Is it possible to replicate vim-surround behaviour when deleting HTML tags? Simple example:

```html
<div cla|ss="container">
  <div class="block"><div>
</div>
```

typing `dst` will leave 2 empty lines and incorrectly indented `<div class="block"></div>`, like this:

```html
  
  <div class="block"><div>
  
```

doing same thing with vim-surround:

```html
<div class="block"><div>
```

**Comment by kylechui** [comment]
Hi there, just wanted to give an update that I am thinking about how to go about this. I originally had something in place that used the builtin `equalprg`, but this caused issues like #46. Perhaps I can try something out with only calling the format command if a file type is defined.

**Comment by kylechui** [comment]
@rorj I don't really want to hard-code an exception case for HTML files into the plugin, but I also don't really know under what circumstances to indent/dedent. I'll keep trying to think of ideas though.

**Comment by rorj** [comment]
Not sure if this behaviour limited to HTML (very noticeable there for sure). I think vim-surround works similarly to blocks like this too:

```
{|
  test,
  anotherOne
}
```

`ds{` or `dsB` here would also remove empty lines and change indentation.

From user perspective I probably never want empty (whitespace only) lines upon deletion and naturally I would expect contents indented automatically in this specific case.

**Comment by kylechui** [comment]
Hi there, I've implemented (a really bad version) the feature you've requested via [add-smart-indentation](https://github.com/kylechui/nvim-surround/tree/add-smart-indentation). The "heuristic" I'm using here is:
If deleting the delimiter pair yields lines that only consist of whitespace, then delete those lines, and dedent the inner contents of the surround.

**Comment by kylechui** [comment]
I'm not sure how to get other people's feedback on how to handle the "empty" lines though---should they be deleted? I'm not 100% sure. I *could* just commit this and wait to see who complains but that seems sub-optimal.

**Comment by kylechui** [comment]
@rorj I've now made it so that indentation *always* occurs when you surround with open/closing pairs, and dedentation always happens when you delete open/closing pairs and the lines are whitespace only. Please try the branch out and see what you think.

**Comment by kylechui** [comment]
@andrewferrier Sorry for the tag, but what do you think about the previous comment? E.g. `VSb` on
```lua
test
```
will yield
```lua
(
    test
)
```
and `dsb` will revert to the original buffer contents. I played around with `vim-surround` a bit, and it seems that this exact test case is a bit inconsistent; more precisely, it seems that the indentation *depends on the filetype*. For the previous example, the `test` is indented when the filetype isn't set, but isn't indented when filetype is `html` or `lua`. Is this something where we want `nvim-surround`'s behavior to diverge from `vim-surround`? I think `vim-surround` is using the builtin `equalprg` setting, but it seems like it causes weird behavior sometimes (see #46 when I tried it last).

CC: @Gelio If it's not a big deal, is it alright if I tag you once in a while to ask for your opinion on certain design choices like this? I don't really have many people that use this plugin that I can ask for feedback from, but I would like to do "[what feels natural](https://github.com/kylechui/nvim-surround/blob/main/CONTRIBUTING.md)" to most users.

**Comment by kylechui** [comment]
I think this rule of "always indent/dedent" makes a conceptually simple model for the end user, but I'm unsure if there's any sort of behavior that old `vim-surround` users rely on that I'm unaware of. One of the things I could do is to just push these changes and see if people complain, but I'd like to keep that to a minimum. I'd also appreciate any suggestions on how I can get more community/user feedback on these sorts of design-level decisions!

**Comment by jonatan-branting** [comment]
I'd say you should just commit to it and collect feedback that way. It's still early days for this plugin after all :)

**Comment by Gelio** [comment]
> CC: @Gelio If it's not a big deal, is it alright if I tag you once in a while to ask for your opinion on certain design choices like this? I don't really have many people that use this plugin that I can ask for feedback from, but I would like to do "[what feels natural](https://github.com/kylechui/nvim-surround/blob/main/CONTRIBUTING.md)" to most users.

Sure, no problem, I appreciate being asked for an opinion :smile: 

---

My opinion on this feature is that it seems entirely optional. I use an automated formatter for all languages that I work on regularly. For HTML, I use [prettier](https://prettier.io/). From my perspective, the exact formatting that nvim-surround leaves in the buffer is going to be changed anyway by prettier after I save the file. Thus, the nvim-surround formatting is only until I save the file. That was also the way I worked with `vim-surround` - when the formatting from various buffer operations got hard to read, I saved the file/invoked `:lua vim.lsp.buf.formatting()` and the formatter got the file into a state that has consistent formatting.

So, all in all, to me this feature is entirely optional. If it complicates the code a lot, I probably would skip adding it and tell users to use an automated formatter instead :sweat_smile:

**Comment by andrewferrier** [comment]
Agree with @Gelio ; don't overcomplicate this logic. I also would use an auto-formatter. And @jonatan-branting is correct also ;), none of what you're talking about here is functionally *wrong*, so you could commit and wait for the complaints to roll in, it's not hard to revert after all! (And eventually you could move to a release model anyway so those who want stability can pin themselves to a branch).

**Comment by kylechui** [comment]
@rorj Is there a particular reason why you're *not* using a formatter? Or any particular use case that you have in mind in which the "smart indenting" would be more helpful to you here?

**Comment by rorj** [comment]
To be honest, I don't follow how using prettier or any other code formatter related to this. I do use it, not on every project though. There are also instances when I edit random code like this, which is not strictly HTML:

```javascript
const str = `
  <div class="container">
    <div class="block"></div>
  </div>
`
```

Regardless, if you use prettier or just manually fix formatting yourself, both are the same in my book — unnecessary extra step.

I've tried mini.surround over the weekend and it implements this feature. If it's not something you want to add to your plugin to keep things simpler or to not break existing behaviour that is understandable.

**Comment by kylechui** [comment]
@jonatan-branting I think `formatprg` is probably not the move here, as by default it seems to join lines until they hit `textwidth`; I'm trying to think if there are any issues with:
* Always indenting when the delimiters are inserted on new lines
* Always dedenting when the delimiters are deleted are on their own line

I tried using `equalprg` (using the `=` operator) before, but it had some weird issues. It's really not that much work to write my own indentation/dedentation functions, so I think I'll opt for that instead.

**Comment by kylechui** [comment]
As a note to myself about possible "intended" behaviors:
```cpp
int main() {
    cout << "Hello world!" << endl;
}
```
`dsB` -> `int main() cout << "Hello world!" << endl;`

**Comment by kylechui** [comment]
Update: This issue is going to be merged into #92, but I think I've found out how to implement this properly, as `:h indentexpr` seems to be set for HTML files.

**Comment by rorj** [comment]
@kylechui I've tried `add-smart-indentation` and it works well. Will try `add-more-keymaps` later this week.

**Comment by kylechui** [comment]
@rorj Sounds good; I don't think `add-smart-indentation` is a good indication of what things will look like since I basically just manually computed indent widths and "guessed" what the indentation level *should* be from there, whereas `add-more-keymaps` uses the builtin `indentexpr` where valid; if you have Tree-sitter installed then that will define an indentation-computing expression for you, resulting in better, more accurate indents. The only caveat (I can think of) is that things might not work as smoothly if no indentation expression is available, e.g. in a scratch buffer.

**Comment by kylechui** [comment]
Honestly I feel like it has been too long since I've created this plugin that I do not feel like potentially breaking end-user configuration. To remove newlines when deleting tags one can modify the `delete` key's pattern to include matching newline characters, e.g.:
```
delete = "^(%b<>\n?)().-(\n?%b<>)()$"
                ^^^      ^^^
```
