### ISSUE TITLE
Highlights not cleared when cancelling `vim.ui.input`

### ISSUE THREAD

**Issue by smjonas** [kylechui/nvim-surround#85]
**Checklist**
- [X] Have you updated the plugin to the latest version on `main` branch?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

**Describe the bug**
When cancelling the `vim.ui.input` prompt, any created highlights will not be cleared and stay permanently in the buffer.

**To Reproduce**
1. Move to any word in a buffer and type `ysiwT`.
2. Press `<C-c>`.

**Expected behavior**
The highlight should be cleared.

**Additional context**
None

**Comment by kylechui** [comment]
Interesting... continuing the discussion here this seems like even more of a niche problem than I thought; this only happens when you use `<C-c>` to terminate the input, as opposed to `<Esc>` (which I normally use).

**Comment by smjonas** [comment]
I think this is just the way Neovim's `vim.fn.input` / `vim.ui.input` work in general: cancelling normally, i.e. by closing the command line (I mapped this to `ii`, works with `<esc>` by default) returns `nil` as an input. However, `<C-c>` as a keyboard interrupt is somehow considered an error. Maybe this behavior should be changed in Neovim / Vim  itself.

**Comment by kylechui** [comment]
While I agree, I don't think that's going to be changed anytime soon for parity reasons with Vim haha, as `vim.fn.input()` is just an internal call to VimL's `input()`(to my knowledge).
