### ISSUE TITLE
Support for ranges (e.g. `2ysiw`)

### ISSUE THREAD

**Issue by smjonas** [kylechui/nvim-surround#86]
**Checklist**
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

**Is your feature request related to a problem? Please describe.**
Sometimes, one wants to surround multiple words. E.g. surrounding `two words` to get `(two words)`. This is where a command like `2ysiw"` would be useful. 

**Additional context**
Caveats: this does not sound like a trivial feature to implement. 

Here are some examples of how I would imagine this feature to behave (`|` is the cursor position):
- Line `|these (are) (words)`, keyboard input: `2dsb`, expected output: `|these (are) words`
- Line `|these ((words))`, keyboard input: `2dsb`, expected output: `|these (words)`

Essentially, this moves to the right, then outwards until a match (here: brackets) is found.

For `ysiw`, it would just move to the right instead until the second word was found.

Let me know if you think this feature is even feasible to implement :)

**Comment by VladimirMarkelov** [comment]
> Line |these ((words)), keyboard input: 2dsb, expected output: |these (words)

To me, it looks a bit confusing as the command is ambiguous. I read the command `2dsb` as `delete brackets 2 times`, so applying the command to `these ((word|s))` I expect to get `these word|s`. But in your examples `2` is for the last command `w`, not for the entire command which is unexpected.

Anyway, deleting multiple brackets with `#dsb` sometimes useful as well.

**Comment by kylechui** [comment]
I agree with @VladimirMarkelov's interpretation as well; IMO to keep this plugin from growing to become too complex, some things need to remain "with the user". In this case, I don't think it would be a trivial thing to add, nor a very common occurrence that people face (that they wouldn't just move the cursor for). I'm open to hearing other feedback though, so let me know what other thoughts you might have!

**Comment by NoahTheDuke** [comment]
To achieve this without the plugin, select the words first and then wrap: `v2wS"`

**Comment by smjonas** [comment]
> [...] I expect to get `these word|s`. But in your examples `2` is for the last command `w`, not for the entire command which is unexpected.

Yes, sorry that is actually what I meant! I have updated the description.

> To achieve this without the plugin, select the words first and then wrap: v2wS"

Yup, while that would definitely work, I am kind of used to typing the range first. Another plugin that supports something similar is `targets.vim` (which supports `dinq` to delete inside the second-next quote). So that would be another idea.

**Comment by kylechui** [comment]
@smjonas I didn't read your feature enhancement properly; your original question and additional context are actually addressing two separate items. You can use @NoahTheDuke's suggestion, or `ys2aw"`. The reasoning behind this is that `ys` takes a text object and character as "input", so if you want to surround the next two words then `2aw` is the text object you want to be using. Hopefully that clears some things up!

**Comment by smjonas** [comment]
> I read the command `2dsb` as `delete brackets 2 times`, so applying the command to `these ((word|s))` I expect to get `these word|s`.

You are absolutely right, that makes a lot more sense and I find that more logical as well!
Maybe we could take inspiration from `targets.vim` which supports `dinq` to delete inside the next quotes? Then `dsnq` could turn `"first" "second"` into`"first" second`. Just an idea.

> To achieve this without the plugin, select the words first and then wrap: v2wS"

Sure, but I feel this feels less "vimmy" (you normally type the operation first (e.g. `d`), then the next object). So this feels less intuitive to me, at least for me.

**Comment by smjonas** [comment]
> @smjonas I didn't read your feature enhancement properly; your original question and additional context are actually addressing two separate items. You can use @NoahTheDuke's suggestion, or `ys2aw"`. The reasoning behind this is that `ys` takes a text object and character as "input", so if you want to surround the next two words then `2aw` is the text object you want to be using. Hopefully that clears some things up!

Thank you, I did not know this already works, that helps for sure!

**Comment by kylechui** [comment]
I'm not 100% sure, but I think there's a slight chance that `dsnq` might work if you have `targets.vim` installed, due to the way things are implemented "behind-the-scenes". Also if my comment resolved your question, can you close this issue?

**Comment by smjonas** [comment]
Unfortunately, `dsnq` behaves strangely: it inserts a single `p` character in an unrelated line (`p` was somehow placed into the `.` register).

**Comment by kylechui** [comment]
I just realized that this wouldn't make sense for deletions/changes since that's not how I've implemented things; maybe close this issue and create a feature request about adding `targets.vim` support? This *does* work for adding new surrounds though, e.g. `ysanq)`.

**Comment by smjonas** [comment]
Yes, sure I'll do that then! Thanks for all your feedback :)
